import { readPreparedView } from './prepared-views';
import { LoadingRing } from './ModuleLoading';
import { useEffect, useRef, useState } from 'react';
import type { HubAgent, HubMember, HubState } from '../../../packages/domain/agent-hub';
import { deskAvailable, hubWorldSize, roomTemplates, roomFurniture, furnitureChoices, type FurnitureKind, type HubLayout, type HubRoom, type RoomTemplate } from '../../../packages/domain/hub-layout';
import type { Entity, Snapshot, Task } from '../../../packages/domain/contracts';
import { ApiError, readLocal, request, saveLocal } from './api';
import { retainedWindowId } from './useWorkspace';
import { Portrait } from './nova/lynx-portrait/Portrait';
import { AssignmentReview } from './AssignmentReview';
import { ComposerMenu } from './ComposerMenu';
import { Dialog } from './ui';
import { Plus, Search, MoreHorizontal, X } from './icons';
import './agent-hub.css';
import { HubMeetingPanel } from './HubMeetingPanel';
import type { HubMeetingState } from '../../../packages/domain/hub-meetings';
import type { HubInteraction } from './nova/lynx-pixel/HubPopulation';
import PixelHub from './nova/lynx-pixel/PixelHub';
import { observeHubPerformance } from './nova/lynx-pixel/hub-performance';

type Actions = { openWork?: (conversationId: string) => void; assignWork: (agentId: string) => void; openAgent: (id?: string) => void; openPlan: (id: string) => void; openRoutine: (id: string) => void; openContent: (id: string) => void; editTask: (task: Entity<Task>) => void };
type Props = Actions & { snapshot: Snapshot; presentation: 'team' | 'hub'; setPresentation: (view: 'team' | 'hub') => void; manage: (view: 'assignment' | 'routines' | 'skills') => void; unfinished: string[] };
type LayoutAction = { type: 'furnish-room'; roomId: string; slot: string; furniture: FurnitureKind } | { type: 'add-room'; template: Exclude<RoomTemplate, 'commons'>; name: string } | { type: 'rename-room'; roomId: string; name: string } | { type: 'place-agent'; agentId: string; roomId: string; desk: number };
type LayoutCommand = { requestId: string; epoch: string; expectedRevision: number; action: LayoutAction };
const statusLabel = (member: HubMember) => ({ working: 'Working', 'waiting-owner': 'Needs review', 'waiting-provider': 'Waiting for worker', failed: 'Failed', idle: 'Ready', offline: 'Offline' })[member.status];
export default function AgentHub({ snapshot, presentation, setPresentation, manage, unfinished, ...actions }: Props) {
  const key = `e3:hub:${snapshot.epoch}:${snapshot.deviceId}:${retainedWindowId}`;
  const [state, setState] = useState<HubState | undefined>(() => readPreparedView(snapshot, 'agents/hub?archived=false')), [error, setError] = useState(''), [readError, setReadError] = useState(''), [selected, setSelected] = useState<string | undefined>(() => readLocal(key + ':selected'));
  const [query, setQuery] = useState(''), [archived, setArchived] = useState(false), [revision, reload] = useState(0), [detail, setDetail] = useState<string>();
  const [meetings,setMeetings]=useState<HubMeetingState>(),[meetingError,setMeetingError]=useState(''),[meetingOpen,setMeetingOpen]=useState(false),[meetingTick,bumpMeeting]=useState(0);
  const [interaction,setInteraction]=useState<HubInteraction>();
  const [zoom, setZoom] = useState(() => readLocal<number>(key + ':zoom') ?? .8);
  const [roomForm, setRoomForm] = useState<{ id?: string; name: string; template: Exclude<RoomTemplate, 'commons'> } | undefined>(() => readLocal(key + ':room-form'));
  const [pending, setPending] = useState<LayoutCommand | undefined>(() => readLocal(key + ':pending')), [busy, setBusy] = useState(false);
  const mounted = useRef(true), flight = useRef(false), opener = useRef<HTMLElement | null>(null), closeButton = useRef<HTMLButtonElement>(null);
  const viewport = useRef<HTMLDivElement>(null);
  const [windowBounds, setWindowBounds] = useState({ x: 0, y: 0, width: 1400, height: 1000 });
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>;
    const poll = async () => {
      try {
        const params = new URLSearchParams({ archived: String(archived), ...(selected ? { agentId: selected } : {}) });
        const next = await request<HubState>(`agents/hub?${params}`, undefined, controller.signal);
        if (!controller.signal.aborted) { setState(next); setReadError(''); }
      } catch (reason) { if (!controller.signal.aborted) { if (reason instanceof ApiError && reason.code === 'hub_agent') setSelected(undefined); else setReadError(reason instanceof Error ? reason.message : 'Your team could not load.'); } }
      finally { if (!controller.signal.aborted) timer = setTimeout(() => void poll(), 4000); }
    };
    void poll(); return () => { controller.abort(); clearTimeout(timer); };
  }, [archived, selected, revision, snapshot.cursor]);
  useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const value=await request<HubMeetingState>('agents/meetings',undefined,controller.signal);if(!controller.signal.aborted){setMeetings(value);setMeetingError('');}}catch{if(!controller.signal.aborted)setMeetingError('Discussion status is reconnecting. The last saved gathering is shown.');}finally{if(!controller.signal.aborted)timer=setTimeout(()=>void poll(),1800);}};void poll();return()=>{controller.abort();clearTimeout(timer);};},[meetingTick,snapshot.epoch]);
  useEffect(() => { if (selected) closeButton.current?.focus(); }, [selected]);
  useEffect(() => { saveLocal(key + ':selected', selected ?? null); }, [selected, key]);
  useEffect(() => { saveLocal(key + ':room-form', roomForm ?? null); }, [roomForm, key]);
  const updateBounds = () => { const v = viewport.current; if(v){const world=v.querySelector<HTMLElement>('.hub-world');setWindowBounds({x:v.scrollLeft-(world?.offsetLeft??0),y:v.scrollTop-(world?.offsetTop??0),width:v.clientWidth,height:v.clientHeight});} };
  useEffect(() => { const v = viewport.current; if (!v) return; const observer = new ResizeObserver(updateBounds); observer.observe(v); updateBounds(); return () => observer.disconnect(); }, [presentation, !!state]);
  useEffect(() => { if (import.meta.env.DEV && new URLSearchParams(location.search).has('qa-hub-performance') && viewport.current) return observeHubPerformance(viewport.current, new URLSearchParams(location.search).get('qa-hub-performance')==='current'?Math.max(1,state!.roster.length):25); }, [presentation, !!state]);
  useEffect(()=>{const frame=requestAnimationFrame(updateBounds);return()=>cancelAnimationFrame(frame);},[zoom,state?.layout.revision]);
  const close = () => { setSelected(undefined); opener.current?.focus({ preventScroll: true }); };
  const pick = (member: HubMember, element: HTMLElement) => { opener.current = element; setSelected(member.id); };
  const chooseZoom = (value: number) => { const next = Math.min(3, Math.max(.15, value)); setZoom(next); saveLocal(key + ':zoom', next); };
  const changeLayout = async (action?: LayoutAction) => {
    if (flight.current || !state) return;
    const command = pending ?? (action ? { requestId: crypto.randomUUID(), epoch: snapshot.epoch, expectedRevision: state.layout.revision, action } : undefined);
    if (!command) return;
    if (!saveLocal(key + ':pending', command)) { setError('Free browser storage before changing the hub. Your saved layout is kept.'); return; }
    setPending(command); setBusy(true); flight.current = true; setError('');
    try {
      const layout = await request<HubLayout>('agents/hub/layout', command);
      saveLocal(key + ':pending', null);
      if (mounted.current) { setPending(undefined); setState(s => s && ({ ...s, layout })); if (command.action.type !== 'furnish-room') setRoomForm(undefined); reload(r => r + 1);
        if (command.action.type === 'add-room') { const added = layout.rooms.at(-1)!; requestAnimationFrame(() => { viewport.current?.scrollTo({ left: Math.max(0, added.x * 16 * zoom - 40), top: Math.max(0, added.y * 16 * zoom - 40) }); updateBounds(); }); } }
    } catch (reason) {
      if (mounted.current) {
        setError(reason instanceof Error ? reason.message : 'The room change is unconfirmed. Reconcile this same change.');
        if (reason instanceof ApiError && ['hub_changed', 'room_missing', 'agent_unavailable', 'desk_occupied', 'hub_full', 'furniture_slot', 'validation', 'epoch_changed'].includes(reason.code)) { saveLocal(key + ':pending', null); setPending(undefined); reload(r => r + 1); }
      }
    } finally { flight.current = false; if (mounted.current) setBusy(false); }
  };
  const openTask = async (id: string) => { try { const next = await request<Snapshot>('snapshot'), task = next.tasks.find(t => t.id === id); if (mounted.current) { if (task) actions.editTask(task); else setError('The original Task is unavailable. Its link is kept.'); } } catch (reason) { if (mounted.current) setError(reason instanceof Error ? reason.message : 'The Task could not load.'); } };
  const member = state?.roster.find(a => a.id === selected), current = state?.agents.find(a => a.id === selected);
  const filtered = state?.roster.filter(a => `${a.name} ${a.position}`.toLocaleLowerCase().includes(query.toLocaleLowerCase().trim())) ?? [];
  const scale = 16 * zoom, world = state && hubWorldSize(state.layout);
  const visibleRooms = state?.layout.rooms.filter(r => { const t = roomTemplates[r.template]; return r.x * scale < windowBounds.x + windowBounds.width + 200 && (r.x + t.width) * scale > windowBounds.x - 200 && r.y * scale < windowBounds.y + windowBounds.height + 200 && (r.y + t.height) * scale > windowBounds.y - 200; }) ?? [];
  const findInHub = (id: string) => { const p = state?.layout.placements[id], r = state?.layout.rooms.find(r => r.id === p?.roomId); if (!r || !viewport.current) return; viewport.current.scrollTo({ left: Math.max(0, r.x * scale - 50), top: Math.max(0, r.y * scale - 50), behavior: 'auto' }); updateBounds(); };
  return <section className="agent-hub" aria-label="Agents">
    <header className="hub-toolbar"><div className="hub-heading"><h1>Agents</h1>{state && <span className="metadata">{state.total}</span>}</div><div className="hub-header-actions"><div className="hub-switch" aria-label="Team presentation"><button aria-pressed={presentation === 'team'} onClick={() => setPresentation('team')}>Team</button><button aria-pressed={presentation === 'hub'} onClick={() => setPresentation('hub')}>Hub</button></div><button className="primary" onClick={() => actions.openAgent()}><Plus size={18}/>Create agent</button><ComposerMenu label="Team options" icon={<MoreHorizontal size={20}/>} align="right" placement="below">{dismiss => <><button onClick={() => { dismiss(); setArchived(a => !a); setSelected(undefined); }}>{archived ? 'Show current team' : 'Archived agents'}</button><button onClick={() => { dismiss(); manage('assignment'); }}>All assignments</button><button onClick={() => { dismiss(); manage('routines'); }}>Manage routines</button><button onClick={() => { dismiss(); manage('skills'); }}>Skill library</button>{unfinished.map((id, i) => <button key={id} onClick={() => { dismiss(); actions.openAgent(id); }}>Resume unfinished agent {i + 1}</button>)}</>}</ComposerMenu></div></header>
    <div className="hub-searchbar"><label className="search-input"><Search size={18}/><input aria-label="Find an agent" placeholder="Find an agent…" value={query} onChange={e => setQuery(e.target.value)}/></label>{archived && <span className="metadata">Archived agents</span>}{presentation === 'hub' && <><button onClick={()=>{setMeetingOpen(true);const r=state?.layout.rooms.find(r=>r.template==='boardroom');if(r)viewport.current?.scrollTo({left:Math.max(0,r.x*scale-25),top:Math.max(0,r.y*scale-25),behavior:'auto'});}}>Boardroom{meetingError?' · Reconnecting':meetings?.current?.state==='running'?' · Discussing':''}</button><span className="metadata hub-room-count">{state?.layout.rooms.length ?? 0} rooms</span><button disabled={busy || !!pending} onClick={() => setRoomForm({ name: 'Private office', template: 'private' })}><Plus size={16}/>Add room</button></>}</div>
    {(error || readError) && <p className="field-error" role="alert">{error || readError}</p>}{pending && <div className="notice"><span>A room change needs confirmation.</span><button disabled={busy} onClick={() => void changeLayout()}>{busy ? 'Checking…' : 'Reconcile change'}</button></div>}
    {!state && !error && <LoadingRing label="Opening your saved team…"/>}
    {presentation === 'team' ? <div className="hub-team-list"><div className="hub-team-columns metadata"><span>Agent</span><span>Current work</span><span>Status</span></div>{filtered.map(agent => <button className="hub-team-row" key={agent.id} aria-pressed={selected === agent.id} onClick={e => pick(agent, e.currentTarget)}><span className="hub-person"><Portrait recipe={agent.appearance} size="icon" accessibility={{ mode: 'decorative' }}/><span><strong>{agent.name}</strong><small>{agent.position}</small></span></span><span className="hub-current-work">{agent.status === 'idle' ? 'Available for an assignment' : agent.reason}</span><span className="hub-state" data-state={readError ? 'stale' : agent.status}>{readError ? 'Unavailable' : statusLabel(agent)}</span></button>)}{state && !filtered.length && <p className="hub-list-empty metadata">{query ? 'No matching agents.' : archived ? 'No archived agents.' : 'Create your first agent to get started.'}</p>}</div> : state && world && <div className={`hub-stage${zoom < .5 ? ' hub-overview' : ''}`}><div ref={viewport} className="hub-viewport" tabIndex={0} onScroll={updateBounds} aria-label="Connected headquarters. Click a clear floor tile, or use arrow keys and WASD to walk."><div className="hub-world" data-room-labels={scale>=4} style={{ width: world.width * scale, height: world.height * scale }}>
      <PixelHub layout={state.layout} roster={state.roster} visibleRooms={visibleRooms} scale={scale} selected={selected} stale={!!readError||!!meetingError} pick={pick} editRoom={room => setRoomForm({ id: room.id, name: room.name, template: room.template === 'commons' ? 'meeting' : room.template })} disabled={busy || !!pending} viewport={viewport} ownerAppearance={snapshot.records?.profile.find(p => p.id === 'profile:owner')?.value.appearance} persistenceKey={key + ':explorer'} meeting={meetings?.current??null} interaction={interaction}/>

    </div></div><div className="hub-map-tools"><button aria-label="Zoom out" disabled={zoom <= .15} onClick={() => chooseZoom(zoom - .25)}>−</button><button aria-label="Fit all rooms" onClick={() => { chooseZoom(Math.min(1.25, ((viewport.current?.clientWidth ?? 1000) - 40) / (world.width * 16), ((viewport.current?.clientHeight ?? 600) - 40) / (world.height * 16))); viewport.current?.scrollTo({ left: 0, top: 0, behavior: 'instant' }); }}>{Math.round(zoom * 100)}%</button><button aria-label="Zoom in" disabled={zoom >= 3} onClick={() => chooseZoom(zoom + .25)}>+</button></div><span className="hub-navigation-hint">Click the floor to walk · Arrow keys / WASD</span>{query && <div className="hub-search-results" aria-label="Find in hub">{filtered.map(a => <button key={a.id} onClick={e => { findInHub(a.id); pick(a, e.currentTarget); }}>{a.name}<small>{a.position}</small></button>)}{!filtered.length && <span>No matching agents.</span>}</div>}</div>}
    {member && <aside className="hub-inspector card" aria-label={`${member.name} profile`} onKeyDown={e => { if (e.key === 'Escape') { e.stopPropagation(); close(); } }}><button ref={closeButton} className="icon-button hub-close" aria-label="Close agent profile" onClick={close}><X size={20}/></button><Portrait recipe={member.appearance} size="roster" accessibility={{ mode: 'decorative' }}/><h2>{member.name}</h2><p>{member.position}</p><span className="hub-state" data-state={member.status}>{statusLabel(member)}</span><p className="metadata">{snapshot.records?.agent.find(a => a.id === member.id)?.value.purpose}</p><div className="button-row"><button onClick={() => actions.openAgent(member.id)}>Edit agent</button><button className="primary" disabled={member.archived} onClick={() => actions.assignWork(member.id)}>Assign work</button></div>{presentation==='hub'&&!member.archived&&<div className="hub-social-actions" aria-label="Hub interactions">{([['hello','Say hello'],['coffee','Coffee break'],['chat','Chat in commons'],['office','Return to office']] as const).map(([type,label])=><button key={type} disabled={member.status==='working'||!!readError||!!meetingError||!!meetings?.current?.attendees.some(a=>a.id===member.id)} onClick={()=>setInteraction({id:crypto.randomUUID(),agentId:member.id,type})}>{label}</button>)}</div>}{current ? <AgentWork current={current} actions={actions} inspect={setDetail} openTask={openTask} manage={manage}/> : <LoadingRing label="Opening saved work…"/>}{state && !member.archived && <details><summary>Workspace</summary><p className="metadata">Choose an unoccupied private office. Each agent has their own room.</p><select aria-label={`Workspace for ${member.name}`} disabled={busy || !!pending} value={JSON.stringify(state.layout.placements[member.id])} onChange={e => { const placement = JSON.parse(e.target.value); void changeLayout({ type: 'place-agent', agentId: member.id, ...placement }); }}>{state.layout.rooms.flatMap(r => roomTemplates[r.template].desks.map((_, desk) => ({ roomId: r.id, desk, name: r.name }))).filter(p => deskAvailable(state.layout, p, member.id)).map(p => <option key={`${p.roomId}/${p.desk}`} value={JSON.stringify({ roomId: p.roomId, desk: p.desk })}>{p.name} · Desk {p.desk + 1}</option>)}</select></details>}</aside>}
    {roomForm && <Dialog title={roomForm.id ? 'Room settings' : 'Add room'} close={() => { if (!busy) setRoomForm(undefined); }}><form onSubmit={e => { e.preventDefault(); void changeLayout(roomForm.id ? { type: 'rename-room', roomId: roomForm.id, name: roomForm.name } : { type: 'add-room', template: roomForm.template, name: roomForm.name }); }}><label>Name<input required maxLength={80} value={roomForm.name} onChange={e => setRoomForm({ ...roomForm, name: e.target.value })}/></label>{!roomForm.id && <label>Room type<select value={roomForm.template} onChange={e => setRoomForm({ ...roomForm, template: e.target.value as typeof roomForm.template })}><option value="private">Private office · 1 agent</option><option value="studio">Shared studio · additional space</option><option value="meeting">Small meeting room</option><option value="boardroom">Boardroom · long table and 12 chairs</option></select></label>}{roomForm.id && state && <div className="hub-room-furnishings">{roomFurniture(state.layout.rooms.find(room => room.id === roomForm.id)!).map(item => <label key={item.id}>{item.name}<select value={item.kind} disabled={busy || !!pending} onChange={e => void changeLayout({ type: 'furnish-room', roomId: roomForm.id!, slot: item.id, furniture: e.target.value as FurnitureKind })}>{item.choices.map(kind => <option key={kind} value={kind}>{furnitureChoices[kind]}</option>)}</select></label>)}</div>}{error && <p role="alert" className="field-error">{error}</p>}<div className="button-row"><button type="button" disabled={busy} onClick={() => setRoomForm(undefined)}>Close</button><button className="primary" disabled={busy || !!pending || !roomForm.name.trim()}>{busy ? 'Saving…' : roomForm.id ? 'Save name' : 'Add room'}</button></div></form></Dialog>}
    {meetingOpen&&state&&<HubMeetingPanel unavailable={meetingError} state={meetings} roster={state.roster.filter(a=>!a.archived)} layout={state.layout} epoch={snapshot.epoch} draftKey={key+':meeting-draft'} refresh={()=>bumpMeeting(v=>v+1)} close={()=>setMeetingOpen(false)}/>}
    {detail && <AssignmentReview id={detail} close={() => setDetail(undefined)}/>}
  </section>;
}
function AgentWork({ current, actions, inspect, openTask, manage }: { current: HubAgent; actions: Actions; inspect: (id: string) => void; openTask: (id: string) => Promise<void>; manage: Props['manage'] }) {
  return <><section className="hub-current-card"><h3>Current work</h3><p>{current.reason}</p>{current.team?.conversationId&&actions.openWork&&<button onClick={()=>actions.openWork!(current.team!.conversationId!)}>Open team conversation</button>}{current.reviews.map(review => <button className="hub-work-link" key={review.attemptId} onClick={() => actions.openPlan(review.assignmentId)}>Review changes · {review.title}<small>{review.count} to review</small></button>)}{current.active && <button onClick={() => actions.openPlan(current.active!.assignmentId)}>Open assignment</button>}{!current.active && current.latest && <><strong>{current.latest.title}</strong><p className="metadata">{current.latest.message}</p><button onClick={() => actions.openPlan(current.latest!.assignmentId)}>Open result & history</button></>}</section>{!!current.plans.length && <details><summary>Assignments · {current.plans.length}</summary>{current.plans.map(p => <button className="hub-work-link" key={p.id} onClick={() => actions.openPlan(p.id)}>{p.title}</button>)}</details>}<details><summary>Routines{current.routines.length ? ` · ${current.routines.length}` : ''}</summary>{current.routines.map(r => <button className="hub-work-link" key={r.id} onClick={() => actions.openRoutine(r.id)}>{r.name}<small>{r.attention ? 'Needs review' : r.nextAt ? new Date(r.nextAt).toLocaleString() : 'Paused'}</small></button>)}<button onClick={() => manage('routines')}>Manage routines</button></details>{(!!current.tasks.length || !!current.content.length) && <details><summary>Linked work</summary>{current.tasks.map(t => <button className="hub-work-link" key={t.id} onClick={() => void openTask(t.id)}>{t.title}<small>{t.status}</small></button>)}{current.content.map(c => <button className="hub-work-link" key={c.id} onClick={() => actions.openContent(c.id)}>{c.title}<small>{c.stage}</small></button>)}</details>}<details><summary>Skills & capabilities</summary><button onClick={() => actions.openAgent(current.id)}>Edit workspace capabilities</button><button onClick={() => manage('skills')}>Open skill library & reviews</button></details>{current.latest && <details><summary>Activity details</summary><p className="metadata">{current.returned} returned attempts · {current.appliedChanges} applied workspace changes · {current.unresolved} attempts need checking</p><button onClick={() => inspect(current.latest!.id)}>Review saved inputs</button></details>}</>;
}
