import { useEffect, useState } from 'react';
import type { AssignmentAttempt, AssignmentCapture } from '../../../packages/domain/assignments';
import type { Contact, Content, ContentAssignmentSource } from '../../../packages/domain/workspace-records';
import { request } from './api';
import { Dialog } from './ui';

type Reading = { fileId: string; name: string; page: number; pages: number; view: 'text' | 'image'; truncated: boolean; at: string };
type Detail = { attempt: AssignmentAttempt; capture: AssignmentCapture; readings?: Reading[] };
export function AssignmentReview({ id, close, expected }: { id: string; close: () => void; expected?: ContentAssignmentSource }) {
  const [detail, setDetail] = useState<Detail>(), [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); void request<Detail>(`assignments/attempt/${id}`, undefined, controller.signal).then(result => {
    const attempt = result.attempt;
    if (expected && (attempt.id !== expected.attemptId || attempt.assignmentId !== expected.assignmentId || attempt.assignmentRevision !== expected.assignmentRevision || attempt.agentId !== expected.agentId || attempt.agentRevision !== expected.agentRevision || attempt.runId !== expected.runId || attempt.nativeSessionId !== expected.nativeId || attempt.terminal?.turnId !== expected.turnId || attempt.result?.file.id !== expected.fileId || attempt.result.file.sha256 !== expected.sha256)) throw new Error('The original assignment result could not be matched. The Content draft and its original file remain available.');
    if (!controller.signal.aborted) setDetail(result);
  }).catch(reason => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : 'Saved inputs could not load.'); }); return () => controller.abort(); }, [id]);
  return <Dialog title="Saved assignment inputs" close={close}>{error && <p role="alert">{error}</p>}{detail ? <><p className="metadata">These versions were captured at the start. Later edits do not change this attempt.</p><h3>{detail.capture.plan.value.title} · version {detail.capture.plan.revision}</h3><p>{detail.capture.plan.value.brief}</p><p>{detail.capture.plan.value.expectedOutput}</p><h3>{detail.capture.agent.value.name} · design version {detail.capture.agent.revision}</h3><dl className="assignment-captured-source">{Object.entries({position: 'Position', purpose: 'Purpose', instructions: 'Instructions', knowledge: 'Supplied knowledge', nonGoals: 'Limits', reviewCriteria: 'Review criteria'}).map(([field, label]) => { const text = detail.capture.agent.value[field as keyof typeof detail.capture.agent.value]; return typeof text === 'string' && text.trim() ? <div key={field}><dt>{label}</dt><dd>{text}</dd></div> : null; })}</dl>{detail.capture.project && <><h3>Project · {detail.capture.project.value.name}</h3><p>{detail.capture.project.value.purpose}</p></>}{detail.capture.files && <section><h3>Captured source files</h3>{detail.capture.files.length ? detail.capture.files.map(source => <details key={source.file.id}><summary>{source.file.name} · {source.file.size.toLocaleString()} bytes · complete text</summary><p className="metadata">{source.origins.join(" · ")}</p><pre className="assignment-result">{source.text}</pre></details>) : <p className="metadata">No inline text files were included.</p>}</section>}{!!detail.capture.binaryFiles?.length && <section><h3>PDF & image sources</h3><p className="metadata">These exact files were available to the agent. Availability alone does not mean they were inspected.</p>{detail.capture.binaryFiles.map(source => <p key={source.file.id}><strong>{source.file.name}</strong> · {source.file.size.toLocaleString()} bytes<br/><span className="metadata">{source.origins.join(' · ')}</span></p>)}</section>}{!!detail.capture.binaryFiles?.length && <section><h3>Recorded source readings</h3>{detail.readings?.length ? <ul>{detail.readings.map(reading => <li key={`${reading.fileId}:${reading.page}:${reading.view}`}>{reading.name} · page {reading.page} of {reading.pages} · {reading.view === 'image' ? 'image pixels' : 'text'}{reading.truncated ? ' · incomplete excerpt' : ''}</li>)}</ul> : <p className="metadata">No source-tool reading has been recorded for this attempt.</p>}</section>}{detail.capture.sources.map(source => <section key={source.record.id}><h3>{'title' in source.record.value ? source.record.value.title : source.record.value.name} · version {source.record.revision}</h3><CapturedSource value={source.record.value}/></section>)}</> : !error && <p role="status">Loading captured inputs…</p>}</Dialog>;
}

function CapturedSource({ value }: { value: Contact | Content }) {
  const labels: Record<string, string> = { name: 'Name', position: 'Position', organization: 'Organization', email: 'Email', phone: 'Phone', handle: 'Handle', timezone: 'Timezone', category: 'Category', notes: 'Private notes', title: 'Title', brief: 'Brief', body: 'Draft', format: 'Format', platform: 'Platform', stage: 'Stage', plannedDate: 'Planned date' };
  return <dl className="assignment-captured-source">{Object.entries(labels).map(([field, label]) => { const text = (value as unknown as Record<string, unknown>)[field]; return typeof text === 'string' && text ? <div key={field}><dt>{label}</dt><dd>{field === 'body' ? <pre className="assignment-result">{text}</pre> : text}</dd></div> : null; })}{'tags' in value && !!(value.tags ?? []).length && <div><dt>Tags</dt><dd>{(value.tags ?? []).join(', ')}</dd></div>}{'assets' in value && !!value.assets?.length && <div><dt>Referenced files</dt><dd>{value.assets.map(asset => asset.name).join(', ')}</dd></div>}</dl>;
}
