import { LoadingRing } from './ModuleLoading';
import { useEffect, useRef, useState } from 'react';
import type { z } from 'zod';
import type { Entity, Snapshot, Task } from '../../../packages/domain/contracts';
import { addDays, calendarWindow, calendarSelectionSchema, type CalendarDisplayEvent, type CalendarRange, type CalendarSelection, type CalendarState, type LocalCalendarOccurrence } from '../../../packages/domain/calendar';
import { clockInZone, dayStart, eventDates } from '../../../packages/domain/calendar-time';
import { dayEventLayout } from '../../../packages/domain/calendar-layout';
import { dayInZone } from '../../../packages/domain/tasks';
import { ApiError, readLocal, request, saveLocal } from './api';
import { ArrowRight, CalendarDays, CheckSquare2, Plus, RefreshCw, Settings2 } from './icons';
import { Dialog, Empty } from './ui';
import { LocalEventEditor, type EventDraft } from './LocalEventEditor';
import { calendarWindowIdentity } from './calendar-window';
import { CalendarEditScope } from './CalendarEditScope';

type Props = { snapshot: Snapshot; online: boolean; editTask: (task: Entity<Task>) => void; openSettings: () => void };
type Journal = { day: string; view: 'month' | 'week' | 'day'; draft?: EventDraft; editorOpen?: boolean; selection?: z.infer<typeof calendarSelectionSchema>; selectionReview?: boolean };
const dateLabel = (day: string, options: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' }) => new Intl.DateTimeFormat(undefined, { ...options, timeZone: 'UTC' }).format(new Date(day + 'T12:00:00Z'));
const sameRange = (a: CalendarRange, b: CalendarRange) => a.from === b.from && a.to === b.to && a.timezone === b.timezone;
function eventLabel(e: CalendarDisplayEvent, zone: string) { return e.warning && e.sourceId === 'local' ? 'Time needs review' : e.interval.kind === 'date' ? 'All day' : `${clockInZone(e.interval.start, zone)}–${clockInZone(e.interval.end, zone)}`; }
export function Calendar(props: Props) {
  const [identity, setIdentity] = useState<{ id: string; previous?: string }>();
  useEffect(() => { let active = true; void calendarWindowIdentity().then(id => { if (active) setIdentity(id); }); return () => { active = false; }; }, []);
  return identity ? <CalendarWorkspace key={props.snapshot.deviceId + identity.id} {...props} identity={identity}/> : <main className="page-scroll"><LoadingRing label="Opening your calendar…"/></main>;
}
function CalendarWorkspace({ snapshot, online, editTask, openSettings, identity }: Props & { identity: { id: string; previous?: string } }) {
  const key = `e3:calendar:${snapshot.deviceId}:${identity.id}`, timezone = snapshot.layout.value.timezone, today = dayInZone(timezone);
  const [journal, setJournal] = useState<Journal>(() => readLocal<Journal>(key) ?? (identity.previous ? readLocal<Journal>(`e3:calendar:${snapshot.deviceId}:${identity.previous}`) : undefined) ?? { day: today, view: matchMedia('(max-width:650px)').matches ? 'day' : 'month' });
  const timeline = useRef<HTMLDivElement>(null);
  const kept = useRef(journal), alive = useRef(true), sequence = useRef(0), busyRef = useRef(false);
  const [state, setState] = useState<CalendarState>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [inspector, setInspector] = useState<CalendarDisplayEvent>(), [sourcesOpen, setSourcesOpen] = useState(false), [scopeEvent, setScopeEvent] = useState<LocalCalendarOccurrence>();
  const range: CalendarRange = { ...calendarWindow(journal.day, journal.view), timezone }, currentRange = useRef(range); currentRange.current = range;
  const currentEpoch = useRef(snapshot.epoch); currentEpoch.current = snapshot.epoch;
  const keep = (patch: Partial<Journal>) => { const next = { ...kept.current, ...patch }; kept.current = next; setJournal(next); const ok = saveLocal(key, next); if (!ok) setError('Browser storage is full. Keep this window open to preserve your calendar changes.'); return ok; };
  const load = async () => {
    const order = ++sequence.current, captured = currentRange.current, epoch = currentEpoch.current;
    try { const result = await request<CalendarState>(`calendar/state?${new URLSearchParams(captured)}`); if (alive.current && order === sequence.current && epoch === currentEpoch.current && sameRange(captured, currentRange.current) && result.epoch === epoch && result.deviceId === snapshot.deviceId) { setState(result); } }
    catch (reason) { if (alive.current && order === sequence.current) setError(reason instanceof Error ? reason.message : 'The calendar is unavailable. Saved work is kept.'); }
  };
  useEffect(() => { alive.current = true; saveLocal(key, kept.current); void load(); const timer = setInterval(() => { if (!document.hidden) void load(); }, 4000); return () => { alive.current = false; sequence.current++; clearInterval(timer); }; }, [range.from, range.to, timezone, snapshot.epoch]);
  const visible = state && sameRange(state.range, range) ? state : undefined;
  useEffect(() => { if (timeline.current && visible) timeline.current.scrollTop = 7 * 64; }, [range.from, range.to, journal.view, !!visible]);
  const select = async (proposal?: Omit<CalendarSelection, 'revision'>) => {
    if (busyRef.current || journal.selectionReview || (!kept.current.selection && !visible)) return;
    const command = kept.current.selection ?? { requestId: crypto.randomUUID(), epoch: snapshot.epoch, expectedRevision: visible!.selection.revision, ...proposal! };
    if (!keep({ selection: command })) return; busyRef.current = true; setBusy(true); setError('');
    try { await request('calendar/selection', command); if (alive.current) { keep({ selection: undefined, selectionReview: false }); await load(); } }
    catch (reason) { if (alive.current) { setError(reason instanceof Error ? reason.message : 'The selection is unconfirmed.'); if (reason instanceof ApiError && ['calendar_selection_changed', 'epoch_changed', 'calendar_source_changed'].includes(reason.code)) keep({ selectionReview: true }); } }
    finally { busyRef.current = false; if (alive.current) setBusy(false); }
  };
  useEffect(() => { if (journal.selection && !journal.selectionReview) void select(); }, []);
  const refresh = async (sources: boolean) => {
    if (busyRef.current) return; busyRef.current = true; setBusy(true); setError('');
    try { await request(sources ? 'calendar/sources' : 'calendar/refresh', { requestId: crypto.randomUUID(), epoch: snapshot.epoch, ...(!sources ? { range, sourceIds: visible?.selection.sourceIds.filter(id => visible.sources.some(s => s.id === id && s.state !== 'unavailable')) ?? [] } : {}) }); if (alive.current) await load(); }
    catch (reason) { if (alive.current) setError(reason instanceof Error ? reason.message : 'Refresh is unconfirmed. Check its status before trying again.'); }
    finally { busyRef.current = false; if (alive.current) setBusy(false); }
  };
  const newEvent = (day = journal.day) => {
    if (kept.current.draft) { keep({ editorOpen: true }); return; }
    const value = { title: '', notes: '', location: '', allDay: false, timezone, start: { date: day, time: '09:00' }, end: { date: day, time: '10:00' }, state: 'confirmed' as const, projectId: null, taskId: null };
    keep({ draft: { id: crypto.randomUUID(), epoch: snapshot.epoch, revision: 0, value }, editorOpen: true });
  };
  const editLocal = (event: LocalCalendarOccurrence) => {
    if (kept.current.draft) {
      if (kept.current.draft.id === event.eventId && kept.current.draft.originalDate === event.originalDate) keep({ editorOpen: true });
      else setError('An event draft is kept in this window. Finish it or keep working in another window before editing a different event.');
      return;
    }
    if (event.originalDate) setScopeEvent(event);
    else keep({ draft: { id: event.eventId, revision: event.revision, epoch: snapshot.epoch, value: event.value, scope: 'event' }, editorOpen: true });
    setInspector(undefined);
  };
  const openEvent = (event: CalendarDisplayEvent) => {
    if (event.taskId) { const task = snapshot.tasks.find(t => t.id === event.taskId); if (task) editTask(task); return; }
    const local = visible?.localEvents.find(e => e.id === event.id && event.sourceId === 'local'); if (local) editLocal(local); else setInspector(event);
  };
  const move = (direction: number) => { if (journal.view !== 'month') keep({ day: addDays(journal.day, direction * (journal.view === 'week' ? 7 : 1)) }); else { const date = new Date(journal.day.slice(0, 8) + '01T12:00:00Z'); date.setUTCMonth(date.getUTCMonth() + direction); keep({ day: date.toISOString().slice(0, 10) }); } };
  const otherDrafts = (() => { try { return Object.keys(localStorage).filter(k => k.startsWith(`e3:calendar:${snapshot.deviceId}:`) && k !== key).flatMap(k => { const draft = readLocal<Journal>(k)?.draft; return draft?.value && draft.id ? [{ key: k, draft }] : []; }).filter((entry, index, all) => all.findIndex(e => e.draft.id === entry.draft.id && e.draft.value.title === entry.draft.value.title) === index); } catch { return []; } })();
  const events = visible?.events ?? [], selection = journal.selection ?? visible?.selection, loading = !visible;
  const days = Array.from({ length: journal.view === 'month' ? 42 : journal.view === 'week' ? 7 : 1 }, (_, n) => addDays(range.from, n));
  const forDay = (day: string) => events.filter(e => { const span = eventDates(e.interval, timezone); return span.first <= day && span.last >= day; });
  const selectPatch = (patch: Partial<CalendarSelection>) => { if (visible) void select({ sourceIds: visible.selection.sourceIds, showLocal: visible.selection.showLocal, showTasks: visible.selection.showTasks, ...patch }); };
  return <main className="page-scroll calendar-page"><div className="page-intro"><div><span className="eyebrow">A little room for what matters</span><h1>Calendar</h1><p>Your days, together. Local plans and connected calendars.</p></div><button className="primary" onClick={() => newEvent()}><Plus size={19}/>{journal.draft ? 'Continue event draft' : 'New event'}</button></div>
    <section className="calendar-toolbar" aria-label="Calendar navigation"><div className="button-row"><button className="icon-button calendar-prev" aria-label="Previous dates" title="Previous dates" onClick={() => move(-1)}><ArrowRight size={20}/></button><button onClick={() => keep({ day: today })}>Today</button><button className="icon-button" aria-label="Next dates" title="Next dates" onClick={() => move(1)}><ArrowRight size={20}/></button></div><h2>{dateLabel(journal.day, { month: 'long', ...(journal.view !== 'month' ? { day: 'numeric' } : {}), year: 'numeric' })}</h2><div className="calendar-view-switch" aria-label="Calendar view">{(['month', 'week', 'day'] as const).map(view => <button key={view} aria-pressed={view === journal.view} onClick={() => keep({ view })}>{view[0].toUpperCase() + view.slice(1)}</button>)}</div><button aria-expanded={sourcesOpen} onClick={() => setSourcesOpen(v => !v)}><Settings2 size={18}/>Calendars</button></section>
    <div className="calendar-date-row"><label>Go to date<input type="date" value={journal.day} onChange={e => { if (e.target.value) keep({ day: e.target.value }); }}/></label><span>{timezone.replaceAll('_', ' ')} · {events.length} item{events.length === 1 ? '' : 's'} in view</span><button disabled={busy || !online || !visible?.sources.some(s => s.selected && s.state !== 'unavailable')} onClick={() => void refresh(false)}><RefreshCw size={17}/>Refresh events</button></div>
    {error && <div className="notice warning" role="alert"><p>{error}</p><button onClick={() => { setError(''); void load(); }}>Check status</button></div>}
    {journal.selection && <div className="notice"><div><p>{journal.selectionReview ? 'The visible-calendar selection changed in another window. Your selection is kept.' : 'This window has an unconfirmed calendar selection.'}</p><div className="button-row">{journal.selectionReview ? <><button disabled={!visible} onClick={() => { keep({ selection: { ...journal.selection!, requestId: crypto.randomUUID(), epoch: snapshot.epoch, expectedRevision: visible!.selection.revision, sourceIds: journal.selection!.sourceIds.filter(id => visible!.sources.some(s => s.id === id) || visible!.selection.sourceIds.includes(id)) }, selectionReview: false }); }}>Review kept selection</button><button onClick={() => keep({ selection: undefined, selectionReview: false })}>Use current selection</button></> : <button disabled={busy} onClick={() => void select()}>Reconcile selection</button>}</div></div></div>}
    {sourcesOpen && <section className="card calendar-sources"><div className="section-heading"><h2>Visible calendars</h2><button disabled={busy || !online} onClick={() => void refresh(true)}>Refresh sources</button></div><div className="calendar-source-grid"><label className="calendar-check"><input type="checkbox" checked={selection?.showLocal ?? true} disabled={!visible || busy || !!journal.selection} onChange={e => selectPatch({ showLocal: e.target.checked })}/><CalendarDays size={20}/><span>Nova Dream<small>Your editable local events</small></span></label><label className="calendar-check"><input type="checkbox" checked={selection?.showTasks ?? true} disabled={!visible || busy || !!journal.selection} onChange={e => selectPatch({ showTasks: e.target.checked })}/><CheckSquare2 size={20}/><span>Task plans<small>Planning dates; deadlines stay in Tasks</small></span></label>{visible?.sources.map(source => <label className="calendar-check" key={source.id}><input type="checkbox" checked={selection?.sourceIds.includes(source.id) ?? false} disabled={busy || !!journal.selection} onChange={e => selectPatch({ sourceIds: e.target.checked ? [...visible.selection.sourceIds, source.id] : visible.selection.sourceIds.filter(id => id !== source.id) })}/><span>{source.name}<small>{source.accountLabel} · {source.provider === 'google' ? 'Google' : 'Microsoft'}</small><small>{source.state === 'ready' ? 'Up to date' : source.state === 'refreshing' ? 'Refreshing…' : source.state === 'unavailable' ? 'Connection needs attention' : 'Refresh needed'}{source.cache ? ` · checked ${new Date(source.cache.checkedAt).toLocaleTimeString()}` : ''}</small>{source.message && <small>{source.message}</small>}</span></label>)}</div>{visible?.accountMessages.map(m => <p key={m.accountId} className="metadata">{m.label}: {m.message}</p>)}{visible && visible.selection.sourceIds.some(id => !visible.sources.some(s => s.id === id)) && <p className="metadata">Some selected calendars are unavailable. Their selection is kept for reconnection.</p>}<div className="button-row"><button onClick={openSettings}>Connect or manage accounts</button></div>{!visible?.sources.length && <p>Local planning is ready. Connect Google or Microsoft in Settings, then refresh sources.</p>}</section>}
    {visible?.eventsLimited && <p className="calendar-cache-note" role="status">This view reached its event limit. Narrow the dates or select fewer calendars to see more.</p>}
    {visible?.sources.some(s => s.selected && s.state !== 'ready') && <p className="calendar-cache-note" role="status">Some calendars need a refresh. Cached events remain visible; open Calendars for each source’s status.</p>}
    {loading ? <div className="card"><LoadingRing label="Loading these dates…"/></div> : journal.view === 'month' ? <section className="calendar-month" aria-label="Month calendar"><div className="calendar-weekdays">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-month-grid">{days.map(day => { const entries = forDay(day); return <div key={day} className={`calendar-month-day ${day.slice(0, 7) !== journal.day.slice(0, 7) ? 'outside-month' : ''} ${day === today ? 'is-today' : ''}`}><button className="calendar-day-number" aria-label={`Open ${dateLabel(day, { dateStyle: 'full' })}`} onClick={() => keep({ day, view: 'day' })}>{Number(day.slice(8))}</button><div className="calendar-month-events">{entries.slice(0, 3).map(event => <EventButton key={event.sourceId + event.id} event={event} timezone={timezone} open={openEvent}/>)}</div>{entries.length > 3 && <button className="calendar-more" onClick={() => keep({ day, view: 'day' })}>+{entries.length - 3} more</button>}</div>; })}</div></section> : <><div ref={timeline} role="region" className="calendar-timeline-scroll" aria-label={`${journal.view === 'week' ? 'Week' : 'Day'} calendar`} tabIndex={0}><div className={`calendar-timeline ${journal.view}`} style={{ gridTemplateColumns: days.map(day => { const rows = dayEventLayout(forDay(day), dayStart(day, timezone), dayStart(addDays(day, 1), timezone)); const width = Math.max(journal.view === 'week' ? 180 : 220, 68 + Math.max(1, ...rows.map(r => r.columns)) * 64); return `minmax(${width}px, 1fr)`; }).join(' ') }}>{days.map(day => <DayColumn key={day} day={day} today={today} timezone={timezone} events={forDay(day)} open={openEvent} newEvent={() => newEvent(day)}/>)}</div></div><section className="card calendar-agenda"><h2>At a glance</h2>{events.length ? events.map(event => <EventButton key={event.sourceId + event.id} event={event} timezone={timezone} open={openEvent} dated/>) : <Empty title="A little open space.">Add an event or choose connected calendars to shape these days.</Empty>}</section></>}
    {!!otherDrafts.length && <details className="card calendar-cancelled"><summary>Kept event drafts from other windows ({otherDrafts.length})</summary><p>Open a copy to recover your writing. Saving checks the current event before replacing anything.</p>{otherDrafts.map(entry => <button key={entry.key} disabled={!!journal.draft} onClick={() => keep({ draft: entry.draft, editorOpen: true })}>{entry.draft.value.title || 'Untitled event'} · Recover copy</button>)}</details>}
    {!!visible?.localEvents.some(e => e.value.state === 'cancelled') && <details className="card calendar-cancelled"><summary>Cancelled local events in these dates</summary>{visible.localEvents.filter(e => e.value.state === 'cancelled').map(event => <button key={event.id} onClick={() => editLocal(event)}>{event.value.title} · {event.value.start.date} · Review or restore</button>)}</details>}
    {journal.editorOpen && journal.draft && <LocalEventEditor key={journal.draft.id} initial={journal.draft} snapshot={snapshot} persist={draft => keep({ draft })} close={() => keep({ editorOpen: false })} saved={() => { keep({ draft: undefined, editorOpen: false }); void load(); }}/>}
    {scopeEvent && <CalendarEditScope event={scopeEvent} epoch={snapshot.epoch} close={() => setScopeEvent(undefined)} choose={draft => { if (keep({ draft, editorOpen: true })) setScopeEvent(undefined); }}/> }
    {inspector && <Dialog title={inspector.title} close={() => setInspector(undefined)}><div className="calendar-event-details"><p>{dateLabel(eventDates(inspector.interval, timezone).first, { dateStyle: 'full' })} · {eventLabel(inspector, timezone)}</p><p>{visible?.sources.find(s => s.id === inspector.sourceId)?.name} · {visible?.sources.find(s => s.id === inspector.sourceId)?.accountLabel}</p><p>{inspector.status === 'tentative' ? 'Tentative · ' : ''}Read from your provider. Editing connected events is not available in this preview.</p>{inspector.location && <p>{inspector.location}</p>}{inspector.notes && <pre>{inspector.notes}</pre>}{inspector.seriesId && <p className="metadata">This is an occurrence in a recurring series.</p>}<details><summary>Event identity & timing</summary><pre>{JSON.stringify({ providerId: inspector.providerId, interval: inspector.interval, originalTimezone: inspector.originalTimezone, seriesId: inspector.seriesId, originalStart: inspector.originalStart, revisionTag: inspector.revisionTag }, null, 2)}</pre></details></div></Dialog>}
  </main>;
}
function EventButton({ event, timezone, open, dated = false }: { event: CalendarDisplayEvent; timezone: string; open: (e: CalendarDisplayEvent) => void; dated?: boolean }) {
  return <button className={`calendar-event ${event.sourceId === 'tasks' ? 'task-plan' : ''}`} onClick={() => open(event)} title={`${event.title} · ${eventLabel(event, timezone)}`}><span><strong>{event.title}</strong><small>{dated ? dateLabel(eventDates(event.interval, timezone).first) + ' · ' : ''}{eventLabel(event, timezone)}{event.sourceId === 'tasks' ? ' · Task plan' : event.sourceId === 'local' ? event.seriesId ? ' · Repeating local event' : ' · Local event' : ''}</small>{event.warning && <small>{event.warning}</small>}</span></button>;
}
function DayColumn({ day, today, timezone, events, open, newEvent }: { day: string; today: string; timezone: string; events: CalendarDisplayEvent[]; open: (e: CalendarDisplayEvent) => void; newEvent: () => void }) {
  const start = dayStart(day, timezone), end = dayStart(addDays(day, 1), timezone), rows = dayEventLayout(events, start, end), allDay = events.filter(e => e.interval.kind === 'date' && !e.warning), review = events.filter(e => e.interval.kind === 'date' && e.warning);
  const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 60000); return () => clearInterval(timer); }, []);
  const hours = Math.ceil((end - start) / 3600000), clock = (instant: number) => new Intl.DateTimeFormat(undefined, { timeZone: timezone, hour: 'numeric', minute: '2-digit', timeZoneName: 'short' }).format(new Date(instant));
  return <section className={`calendar-day-column ${day === today ? 'is-today' : ''}`} aria-label={dateLabel(day, { dateStyle: 'full' })}><header><h3>{dateLabel(day, { weekday: 'short', day: 'numeric' })}</h3><button className="icon-button" aria-label={`New event on ${day}`} onClick={newEvent}><Plus size={16}/></button></header><div className="calendar-all-day"><span className="metadata">All day</span>{allDay.map(event => <EventButton key={event.sourceId + event.id} event={event} timezone={timezone} open={open}/>)}{review.length > 0 && <div className="calendar-time-review"><span className="metadata">Time needs review</span>{review.map(event => <EventButton key={event.id} event={event} timezone={timezone} open={open}/>)}</div>}</div>{hours === 0 ? <p>This civil date was skipped in this timezone.</p> : <div className="calendar-hours" style={{ height: hours * 64 + 44 }}>{Array.from({ length: hours }, (_, hour) => <div className="calendar-hour-line" style={{ top: hour * 64 }} key={hour}><span>{clock(start + hour * 3600000)}</span></div>)}{rows.map(row => <div key={row.event.sourceId + row.event.id} className="calendar-position" style={{ top: row.top, height: row.height, left: `calc(64px + (100% - 68px) * ${row.column / row.columns})`, width: `calc((100% - 68px) / ${row.columns})` }}><EventButton event={row.event} timezone={timezone} open={open}/></div>)}{now >= start && now < end && <div className="calendar-now" aria-label={`Current time ${clock(now)}`} style={{ top: (now - start) / 3600000 * 64 }}/>}</div>}</section>;
}
