import { useMemo } from 'react';
import { localEventInputSchema, type CalendarRepeat, type LocalCalendarOccurrence, type LocalEventInput } from '../../../packages/domain/calendar';
import { expandLocalCalendar, repeatProblem } from '../../../packages/domain/calendar-repeat';
import { localEventInterval } from '../../../packages/domain/calendar-time';

const weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
export function CalendarRepeatEditor({ value: v, change }: { value: LocalEventInput; change: (patch: Partial<LocalEventInput>) => void }) {
  const r = v.repeat, date = new Date(v.start.date + 'T12:00:00Z');
  const patch = (fields: Partial<CalendarRepeat>) => change({ repeat: { ...r!, ...fields } });
  const preview = useMemo<{ error?: string; occurrences?: LocalCalendarOccurrence[]; limited?: boolean }>(() => {
    const parsed = localEventInputSchema.safeParse({ ...v, title: v.title.trim() || 'Event' });
    if (!parsed.success) return { error: parsed.error.issues[0].message };
    const problem = repeatProblem(parsed.data), timing = localEventInterval(parsed.data);
    if (problem || timing.error) return { error: problem || timing.error };
    if (!v.repeat) return {};
    try { return expandLocalCalendar({ id: 'preview', deviceId: 'preview', revision: 0, updatedAt: '', value: parsed.data }, [], { from: v.start.date, to: '9999-12-28', timezone: v.timezone }, 4); }
    catch { return { error: 'Complete the dates and timezone to preview this repeat.' }; }
  }, [v]);
  return <div className="calendar-repeat"><label>Repeat<select value={r?.cadence ?? ''} onChange={e => {
    if (!e.target.value) change({ repeat: undefined });
    else change({ repeat: { interval: 1, weekdays: [date.getUTCDay()], monthDay: date.getUTCDate(), month: date.getUTCMonth() + 1, monthPattern: 'date', ordinal: Math.ceil(date.getUTCDate() / 7) as CalendarRepeat['ordinal'], weekday: date.getUTCDay(), missingDay: 'skip', ...r, cadence: e.target.value as CalendarRepeat['cadence'] } });
  }}><option value="">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label>
    {r && <div className="calendar-repeat-fields"><label>Repeat every<input type="number" min={1} max={100} required value={r.interval} onChange={e => patch({ interval: Number(e.target.value) })}/><small>{r.cadence === 'daily' ? 'days' : r.cadence === 'weekly' ? 'weeks, starting on Monday' : r.cadence === 'monthly' ? 'months' : 'years'}</small></label>
      {r.cadence === 'weekly' && <div className="weekday-options" role="group" aria-label="Repeat on">{weekdays.map((day, i) => <button key={day} type="button" aria-label={day} aria-pressed={r.weekdays.includes(i)} onClick={() => patch({ weekdays: r.weekdays.includes(i) ? r.weekdays.filter(d => d !== i) : [...r.weekdays, i].sort() })}>{day.slice(0, 3)}</button>)}</div>}
      {['monthly', 'yearly'].includes(r.cadence) && <><div className="form-grid">{r.cadence === 'yearly' && <label>Repeat month<select value={r.month ?? date.getUTCMonth() + 1} onChange={e => patch({ month: Number(e.target.value) })}>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>{new Intl.DateTimeFormat(undefined, { month: 'long', timeZone: 'UTC' }).format(new Date(Date.UTC(2026, i, 1)))}</option>)}</select></label>}<label>Repeat on<select value={r.monthPattern ?? 'date'} onChange={e => patch({ monthPattern: e.target.value as CalendarRepeat['monthPattern'] })}><option value="date">Day of the month</option><option value="weekday">Weekday of the month</option></select></label></div>
        {r.monthPattern === 'weekday' ? <div className="form-grid"><label>Which week<select value={r.ordinal ?? 1} onChange={e => patch({ ordinal: Number(e.target.value) as CalendarRepeat['ordinal'] })}>{[[1, 'First'], [2, 'Second'], [3, 'Third'], [4, 'Fourth'], [5, 'Fifth'], [-1, 'Last']].map(([number, label]) => <option key={number} value={number}>{label}</option>)}</select></label><label>Weekday<select value={r.weekday ?? date.getUTCDay()} onChange={e => patch({ weekday: Number(e.target.value) })}>{weekdays.map((day, i) => <option key={day} value={i}>{day}</option>)}</select></label></div> : <div className="form-grid"><label>Day of month<input required type="number" min={1} max={31} value={r.monthDay ?? date.getUTCDate()} onChange={e => patch({ monthDay: Number(e.target.value) })}/></label><label>If the date is missing<select value={r.missingDay ?? 'skip'} onChange={e => patch({ missingDay: e.target.value as CalendarRepeat['missingDay'] })}><option value="skip">Skip that month</option><option value="last-day">Use the last day</option></select></label></div>}</>}
      <div className="form-grid"><label>Repeat ends<select value={r.count ? 'count' : r.endsOn ? 'date' : 'never'} onChange={e => patch({ count: e.target.value === 'count' ? 10 : undefined, endsOn: e.target.value === 'date' ? v.start.date : undefined })}><option value="never">No end date</option><option value="date">On a date</option><option value="count">After a set count</option></select></label>{r.endsOn && <label>Last start date<input type="date" min={v.start.date} required value={r.endsOn} onChange={e => patch({ endsOn: e.target.value })}/></label>}{r.count !== undefined && <label>Number of events<input type="number" min={1} max={1000} required value={r.count} onChange={e => patch({ count: Number(e.target.value) })}/></label>}</div>
      {!v.allDay && <label>If clocks repeat the start time<select value={v.start.overlap ?? ''} onChange={e => change({ start: { ...v.start, overlap: e.target.value as 'earlier' | 'later' || undefined } })}><option value="">Keep for review</option><option value="earlier">Use earlier time</option><option value="later">Use later time</option></select><small>A start time skipped by the clocks stays visible for review and does not count toward the series total.</small></label>}
      <div className="calendar-repeat-preview" aria-live="polite"><strong>First dates in this series</strong>{preview.error ? <p className="field-error">{preview.error}</p> : <><ul>{preview.occurrences?.map(event => <li key={event.id}>{event.value.start.date}{v.allDay ? ' · All day' : ` · ${event.value.start.time}–${event.value.end.time}`}{event.value.start.date !== event.value.end.date && !v.allDay ? ` (ends ${event.value.end.date})` : ''}{event.problem ? ' · Time needs review' : ''}</li>)}</ul>{!preview.occurrences?.length && <p>No matching dates in the supported date range.</p>}{preview.limited && <p className="metadata">Showing the first four dates.</p>}</>}<p className="metadata">{v.allDay ? 'Each event keeps the same number of calendar days.' : 'The local start time stays fixed. Each event keeps the original elapsed duration when clocks change.'}</p></div>
    </div>}
  </div>;
}
