import { useEffect, useRef, useState } from 'react';
import type { Entity, Snapshot, Task } from '../../../packages/domain/contracts';
import type { Contact } from '../../../packages/domain/workspace-records';
import { activitySchema, organizationSchema, pipelineLabels, pipelineStages, relationshipKinds, relationshipLabels, type ContactActivity, type CrmState, type OrganizationRecord } from '../../../packages/domain/crm';
import { contactMatches, contactDestination } from '../../../packages/domain/contacts';
import { ApiError, readLocal, request, saveLocal } from './api';
import { retainedWindowId } from './useWorkspace';
import { ContactAvatar } from './ContactPhoto';
import { ArrowLeft, CalendarDays, Check, Inbox, Plus, Search, X } from './icons';
import { Empty } from './ui';

type Command<T> = { requestId: string; epoch: string; id: string; expectedRevision: number; value: T; contactId?: string };
/** Form drafts and command identity survive closing, reload and a lost response. */
function useCrmForm<T>(key: string, initial: T, path: string, base: { id: string; revision: number; contactId?: string }, snapshot: Snapshot, saved: () => Promise<void>) {
  const [journal, setJournal] = useState<{ value: T; revision: number; pending?: Command<T> }>(() => readLocal(key) ?? { value: initial, revision: base.revision });
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [rejected, setRejected] = useState(false); const flight = useRef(false);
  const keep = (next: typeof journal) => { if (!saveLocal(key, next)) { setError('Free browser storage before continuing. Your writing remains open.'); return false; } setJournal(next); return true; };
  const change = (value: T) => { if (!busy && !journal.pending) keep({ value, revision: journal.revision }); };
  const submit = async (value = journal.value) => {
    if (flight.current || rejected) return;
    const pending = journal.pending ?? { requestId: crypto.randomUUID(), epoch: snapshot.epoch, id: base.id, expectedRevision: journal.revision, value, ...(base.contactId ? { contactId: base.contactId } : {}) };
    if (!keep({ value: journal.value, revision: journal.revision, pending })) return;
    flight.current = true; setBusy(true); setError('');
    try { await request(path, pending, undefined, 30000); if (!saveLocal(key, null)) throw new Error('Saved. Browser storage could not clear the receipt; reconcile once more.'); setJournal({ value: initial, revision: base.revision }); await saved(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Save is unconfirmed. Reconcile the same request.'); setRejected(e instanceof ApiError && [400, 404, 409, 507].includes(e.status ?? 0)); }
    finally { flight.current = false; setBusy(false); }
  };
  return { value: journal.value, change, submit, error, busy, pending: !!journal.pending, rejected, review: () => { void request<CrmState>('contacts/crm', { epoch: snapshot.epoch, contactId: base.contactId }).then(state => { const current = path === 'contacts/activity' ? state.activities.find(a => a.id === base.id) : state.organizations.find(o => o.id === base.id); if (keep({ value: (current?.value ?? initial) as T, revision: current?.revision ?? 0 })) { setRejected(false); setError(''); } }).catch(e => setError(e instanceof Error ? e.message : 'Saved version could not load.')); } };
}
function SaveState({ form }: { form: { error: string; rejected: boolean; review(): void } }) { return <>{form.error && <p className="field-error" role="alert">{form.error}</p>}{form.rejected && <button onClick={form.review}>Reload saved version</button>}</>; }
export function useContactCrm(snapshot: Snapshot, contactId?: string) {
  const [data, setData] = useState<CrmState>(), [error, setError] = useState('');
  const refresh = async () => { const value = await request<CrmState>('contacts/crm', { epoch: snapshot.epoch, contactId }); setData(value); setError(''); };
  useEffect(() => { const abort = new AbortController(); setError(''); const load = () => request<CrmState>('contacts/crm', { epoch: snapshot.epoch, contactId }, abort.signal).then(value => { if (!abort.signal.aborted) setData(value); }).catch(e => { if (!abort.signal.aborted) setError(e instanceof Error ? e.message : 'Contact context could not load.'); }); void load(); const timer = setInterval(() => void load(), 15000); return () => { clearInterval(timer); abort.abort(); }; }, [snapshot.epoch, snapshot.cursor, contactId]);
  return { data, error, refresh };
}
export function ContactCrmControls({ contact, contacts, snapshot, crm, busy, save, open, organization }: { contact: Entity<Contact>; contacts: Entity<Contact>[]; snapshot: Snapshot; crm?: CrmState; busy: boolean; save(patch: Partial<Contact>): Promise<boolean>; open(id: string): void; organization(name: string): void }) {
  const [reminder, setReminder] = useState(false), [relation, setRelation] = useState(false), [person, setPerson] = useState(''), [kind, setKind] = useState<typeof relationshipKinds[number]>('works_with');
  const cadenceKey = `e3:contact-cadence:${snapshot.deviceId}:${contact.id}:${retainedWindowId}`;
  const [cadence, setCadence] = useState(() => readLocal<NonNullable<Contact['keepInTouch']>>(cadenceKey) ?? contact.value.keepInTouch ?? { days: 30, time: '09:00', timezone: contact.value.timezone });
  const [error, setError] = useState('');
  const updateCadence = (value: typeof cadence) => { setCadence(value); if (!saveLocal(cadenceKey, value)) setError('Reminder edits could not be kept on this device.'); };
  return <section className="crm-profile-tools" aria-label="Relationship details">
    <div className="crm-profile-line"><label>Stage <select aria-label="Relationship stage" disabled={busy || contact.value.archived} value={contact.value.pipelineStage ?? ''} onChange={e => void save({ pipelineStage: e.target.value ? e.target.value as Contact['pipelineStage'] : null })}><option value="">Not tracked</option>{pipelineStages.map(s => <option key={s} value={s}>{pipelineLabels[s]}</option>)}</select></label><button disabled={contact.value.archived} onClick={() => setReminder(v => !v)} aria-expanded={reminder}><CalendarDays size={16}/>{contact.value.keepInTouch ? `Every ${contact.value.keepInTouch.days} days` : 'Keep in touch'}</button><button disabled={contact.value.archived} onClick={() => setRelation(v => !v)} aria-expanded={relation}><Plus size={16}/>Relationship</button></div>
    {contact.value.keepInTouch && crm?.cadence?.nextDate && <p className="metadata">Next follow-up {new Date(crm.cadence.nextDate + 'T12:00:00').toLocaleDateString()} · Resets after a logged call, meeting, message or completed follow-up.</p>}
    {reminder && <form className="crm-inline-form" onSubmit={e => { e.preventDefault(); void save({ keepInTouch: cadence }).then(ok => { if (ok) { saveLocal(cadenceKey, null); setReminder(false); } }); }}><label>Days between check-ins<input type="number" min="1" max="730" required value={cadence.days} onChange={e => updateCadence({ ...cadence, days: Number(e.target.value) })}/></label><label>Reminder time<input type="time" required value={cadence.time} onChange={e => updateCadence({ ...cadence, time: e.target.value })}/></label><span className="metadata">{cadence.timezone.replaceAll('_', ' ')} · Clock changes use the first occurrence or next valid time.</span><div className="button-row"><button disabled={busy}>Save reminder</button>{contact.value.keepInTouch && <button type="button" disabled={busy} onClick={() => void save({ keepInTouch: null }).then(ok => { if (ok) setReminder(false); })}>Turn off reminders</button>}<button type="button" onClick={() => setReminder(false)}>Cancel</button></div></form>}
    {relation && <form className="crm-inline-form" onSubmit={e => { e.preventDefault(); void save({ relationships: [...(contact.value.relationships ?? []), { kind, contactId: person }] }).then(ok => { if (ok) { setRelation(false); setPerson(''); } }); }}><label>Relationship<select value={kind} onChange={e => setKind(e.target.value as typeof kind)}>{relationshipKinds.map(k => <option key={k} value={k}>{relationshipLabels[k]}</option>)}</select></label><label>Person<select required value={person} onChange={e => setPerson(e.target.value)}><option value="">Choose a contact</option>{contacts.filter(c => !c.value.archived && c.id !== contact.id && !contact.value.relationships?.some(r => r.contactId === c.id && r.kind === kind)).map(c => <option key={c.id} value={c.id}>{c.value.name}</option>)}</select></label><div className="button-row"><button disabled={busy || !person}>Add relationship</button><button type="button" onClick={() => setRelation(false)}>Cancel</button></div></form>}
    {!!crm?.relationships.length && <div className="crm-relations">{crm.relationships.map(r => <div key={r.label + r.contactId}><span className="metadata">{r.label}</span><button className="crm-text-button" onClick={() => open(r.contactId)}>{contacts.find(c => c.id === r.contactId)?.value.name ?? 'Contact'}</button>{!r.incoming && !contact.value.archived && <button className="icon-button" disabled={busy} aria-label={`Remove ${r.label.toLowerCase()} relationship`} onClick={() => void save({ relationships: (contact.value.relationships ?? []).filter(v => !(v.kind === r.kind && contactDestination(v.contactId, contacts) === r.contactId)) })}><X size={14}/></button>}</div>)}</div>}
    {(contact.value.organization || contact.value.otherOrganizations?.length) && <div className="crm-organization-links">{[contact.value.organization, ...(contact.value.otherOrganizations ?? [])].filter(Boolean).map(name => <button key={name} className="crm-text-button" onClick={() => organization(name)}>{name}</button>)}</div>}{error && <p role="alert" className="field-error">{error}</p>}
  </section>;
}
export type TimelineItem = { id: string; at: string; type: 'email' | 'meeting' | 'task'; title: string; subtitle?: string; open(): void };
export function ContactTimeline({ contact, snapshot, activities, items, refresh }: { contact: Entity<Contact>; snapshot: Snapshot; activities: ContactActivity[]; items: TimelineItem[]; refresh(): Promise<void> }) {
  const [editing, setEditing] = useState<ContactActivity | 'new'>(), [archived, setArchived] = useState(false);
  const timeline = [...items.map(item => ({ ...item, activity: undefined as ContactActivity | undefined })), ...activities.filter(a => a.value.archived === archived).map(a => ({ id: a.id, at: a.value.at, type: a.value.kind, title: a.value.text, subtitle: a.value.archived ? 'Archived entry' : undefined, open: () => setEditing(a), activity: a }))].sort((a, b) => (Date.parse(b.at) || 0) - (Date.parse(a.at) || 0));
  return <section className="contact-correspondence"><div className="section-heading"><h3>Timeline</h3><div className="button-row"><button className="crm-text-button" aria-pressed={archived} onClick={() => setArchived(v => !v)}>{archived ? 'Show active' : 'Archived entries'}</button><button disabled={contact.value.archived} onClick={() => setEditing('new')}><Plus size={16}/>Log activity</button></div></div>
    {editing && <ActivityEditor key={editing === 'new' ? 'new' : editing.id} contact={contact} snapshot={snapshot} entry={editing === 'new' ? undefined : editing} close={() => setEditing(undefined)} saved={async () => { setEditing(undefined); await refresh(); }}/>}<div className="crm-timeline">{timeline.filter(i => !archived || i.activity).map(item => <button key={item.id} onClick={item.open}><span className="crm-timeline-icon">{item.type === 'email' ? <Inbox size={16}/> : item.type === 'task' ? <Check size={16}/> : <CalendarDays size={16}/>}</span><span><small>{item.type === 'task' ? 'Follow-up' : item.type[0].toUpperCase() + item.type.slice(1)}{item.subtitle ? ' · ' + item.subtitle : ''}</small><strong>{item.title}</strong></span><time>{item.at ? new Date(item.at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : 'Saved link'}</time></button>)}</div>{!timeline.length && <p className="metadata">Activity you log, linked emails, meetings and follow-ups appear here.</p>}</section>;
}
function ActivityEditor({ contact, snapshot, entry, close, saved }: { contact: Entity<Contact>; snapshot: Snapshot; entry?: ContactActivity; close(): void; saved(): Promise<void> }) {
  const key = `e3:crm-activity:${snapshot.deviceId}:${entry?.id ?? contact.id + ':new'}:${retainedWindowId}`;
  const [id] = useState(() => entry?.id ?? readLocal<{ pending?: { id: string } }>(key)?.pending?.id ?? 'activity:' + crypto.randomUUID());
  const form = useCrmForm(key, entry?.value ?? { kind: 'note' as const, at: new Date().toISOString(), text: '', archived: false }, 'contacts/activity', { id, revision: entry?.revision ?? 0, contactId: entry?.contactId ?? contact.id }, snapshot, saved);
  const localDate = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
  return <form className="crm-activity-form" onSubmit={e => { e.preventDefault(); if (activitySchema.safeParse(form.value).success) void form.submit(); }}><div className="crm-inline-form"><label>Activity<select disabled={form.pending} value={form.value.kind} onChange={e => form.change({ ...form.value, kind: e.target.value as ContactActivity['value']['kind'] })}><option value="note">Note</option><option value="call">Call</option><option value="meeting">Meeting</option><option value="message">Message</option></select></label><label>When<input type="datetime-local" required disabled={form.pending} value={localDate(form.value.at)} onChange={e => { if (e.target.value) form.change({ ...form.value, at: new Date(e.target.value).toISOString() }); }}/></label></div><label className="sr-only" htmlFor="crm-activity-text">Activity details</label><textarea id="crm-activity-text" autoFocus required maxLength={10000} disabled={form.pending} placeholder="What happened? What should you remember?" value={form.value.text} onChange={e => form.change({ ...form.value, text: e.target.value })}/><SaveState form={form}/><div className="button-row"><button disabled={contact.value.archived || form.busy || form.rejected || !form.value.text.trim()}>{form.busy ? 'Saving…' : form.pending ? 'Reconcile save' : 'Save activity'}</button>{entry && <button type="button" disabled={contact.value.archived || form.busy || form.pending} onClick={() => void form.submit({ ...form.value, archived: !form.value.archived })}>{form.value.archived ? 'Restore' : 'Archive'}</button>}<button type="button" onClick={close}>Close · writing kept</button></div></form>;
}
export function OrganizationDirectory({ snapshot, refresh, open, selectedName }: { snapshot: Snapshot; refresh(): Promise<void>; open(id: string): void; selectedName?: string }) {
  const crm = useContactCrm(snapshot), [query, setQuery] = useState(''), [selected, setSelected] = useState<string>(), [creating, setCreating] = useState(false), [editing, setEditing] = useState(false);
  useEffect(() => { if (selectedName && crm.data) { const org = crm.data.organizations.find(o => o.value.name === selectedName); if (org) setSelected(org.id); } }, [selectedName, crm.data?.organizations.length]);
  const org = crm.data?.organizations.find(o => o.id === selected), people = snapshot.records?.contact ?? [];
  return <div className={`contacts-workspace${org || creating ? ' has-selection' : ''}`}><section className="contacts-directory" aria-label="Organization directory"><div className="contacts-search"><label className="search-input"><Search size={17}/><input aria-label="Search organizations" placeholder="Search organizations…" value={query} onChange={e => setQuery(e.target.value)}/></label><button className="icon-button" aria-label="New organization" title="New organization" onClick={() => { setCreating(true); setEditing(true); setSelected(undefined); }}><Plus size={18}/></button></div><div className="contacts-rows">{crm.data?.organizations.filter(o => [o.value.name, o.value.industry].join(' ').toLowerCase().includes(query.toLowerCase())).map(o => <button className="contact-row" key={o.id} aria-pressed={selected === o.id} onClick={() => { setSelected(o.id); setCreating(false); setEditing(false); }}><span className="contact-avatar">{o.value.name.slice(0, 1).toUpperCase()}</span><span><strong>{o.value.name}</strong><small>{o.memberIds.length} {o.memberIds.length === 1 ? 'person' : 'people'}{o.value.industry ? ' · ' + o.value.industry : ''}</small></span></button>)}</div>{crm.error && <p role="alert">{crm.error}</p>}</section><section className="contacts-detail" aria-label="Organization details">{org || creating ? <><button className="contact-back" onClick={() => { setSelected(undefined); setCreating(false); }}><ArrowLeft size={17}/>Organizations</button>{editing || creating ? <OrganizationEditor key={org?.id ?? 'new'} organization={org} snapshot={snapshot} close={() => { setEditing(false); setCreating(false); }} saved={async () => { setEditing(false); setCreating(false); await refresh(); await crm.refresh(); }}/>: org && <article className="contact-person"><div className="section-heading"><h2>{org.value.name}</h2><button onClick={() => setEditing(true)}>Edit organization</button></div><dl className="contact-methods">{org.value.industry && <div><dt>Industry</dt><dd>{org.value.industry}</dd></div>}{org.value.website && <div><dt>Website</dt><dd><a href={org.value.website} target="_blank" rel="noreferrer">{org.value.website}</a></dd></div>}{org.value.phone && <div><dt>Phone</dt><dd>{org.value.phone}</dd></div>}</dl>{org.value.notes && <section className="contact-notes"><h3>Organization notes</h3><p>{org.value.notes}</p></section>}<h3>People</h3><div className="crm-organization-people">{people.filter(c => org.memberIds.includes(c.id)).map(c => <button className="contact-row" key={c.id} onClick={() => open(c.id)}><ContactAvatar value={c.value}/><span><strong>{c.value.name}</strong><small>{c.value.position || c.value.email}</small></span></button>)}</div>{!org.memberIds.length && <p className="metadata">Add this organization to a person’s profile to link them here.</p>}</article>}</> : <Empty title="Organizations, together">Choose an organization to see its people and shared context.</Empty>}</section></div>;
}
function OrganizationEditor({ organization, snapshot, saved, close }: { organization?: OrganizationRecord; snapshot: Snapshot; saved(): Promise<void>; close(): void }) {
  const key = `e3:crm-org:${snapshot.deviceId}:${organization?.id ?? 'new'}:${retainedWindowId}`, [id] = useState(() => organization?.id ?? readLocal<{ pending?: { id: string } }>(key)?.pending?.id ?? 'organization:' + crypto.randomUUID());
  const form = useCrmForm(key, organization?.value ?? { name: '', website: '', phone: '', industry: '', notes: '' }, 'contacts/organization', { id, revision: organization?.revision ?? 0 }, snapshot, saved);
  return <form className="crm-organization-form" onSubmit={e => { e.preventDefault(); if (organizationSchema.safeParse(form.value).success) void form.submit(); }}><h2>{organization ? 'Edit organization' : 'New organization'}</h2>{(['name', 'website', 'phone', 'industry'] as const).map(field => <label key={field}>{field[0].toUpperCase() + field.slice(1)}<input type={field === 'website' ? 'url' : 'text'} required={field === 'name'} disabled={form.pending} value={form.value[field]} onChange={e => form.change({ ...form.value, [field]: e.target.value })}/></label>)}<label>Organization notes<textarea disabled={form.pending} value={form.value.notes} onChange={e => form.change({ ...form.value, notes: e.target.value })}/></label>{organization && <p className="metadata">Renaming updates the organization on its people’s profiles.</p>}<SaveState form={form}/><div className="button-row"><button disabled={form.busy || form.rejected || !organizationSchema.safeParse(form.value).success}>{form.busy ? 'Saving…' : form.pending ? 'Reconcile save' : 'Save organization'}</button><button type="button" onClick={close}>Close · writing kept</button></div></form>;
}
export function ContactPipeline({ contacts, open }: { contacts: Entity<Contact>[]; open(id: string): void }) {
  const [query, setQuery] = useState('');
  return <section className="crm-pipeline"><label className="search-input"><Search size={17}/><input aria-label="Search pipeline" placeholder="Find a relationship…" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="crm-pipeline-columns">{pipelineStages.map(stage => { const people = contacts.filter(c => !c.value.archived && c.value.pipelineStage === stage && contactMatches(c.value, query)); return <section key={stage}><h2>{pipelineLabels[stage]} <span>{people.length}</span></h2>{people.map(c => <button className="contact-row" key={c.id} onClick={() => open(c.id)}><ContactAvatar value={c.value}/><span><strong>{c.value.name}</strong><small>{c.value.organization || c.value.position}</small></span></button>)}</section>; })}</div><p className="metadata">Choose a stage on a person’s profile to track that relationship here.</p></section>;
}
