import {lazy,Suspense,useEffect,useState} from 'react';
import type {Entity,Snapshot} from '../../../packages/domain/contracts';
import type {Content} from '../../../packages/domain/workspace-records';
import {contentModes,type ContentJob,type ContentMode,type ContentWorkspaceState} from '../../../packages/domain/content-workspace';
import {assignmentHoldsSlot} from '../../../packages/domain/assignments';
import {readLocal,request,saveLocal} from './api';
const Preview=lazy(()=>import('./ContentPreview'));
const Inputs=lazy(()=>import('./AssignmentReview').then(module=>({default:module.AssignmentReview})));
export function ContentAgentWork({entity,snapshot,state,blocked,run}:{entity:Entity<Content>;snapshot:Snapshot;state?:ContentWorkspaceState;blocked:boolean;run:(input:Record<string,unknown>)=>Promise<any>}){
 const agents=(snapshot.records?.agent??[]).filter(a=>!a.value.archived),key=`e3:content-work-draft:${snapshot.deviceId}:${snapshot.epoch}:${entity.id}`;
 const [draft,setDraft]=useState(()=>readLocal<{mode:ContentMode;agentId:string;instructions:string}>(key)??{mode:'draft',agentId:agents.find(a=>/maker/i.test(a.value.position))?.id??agents[0]?.id??'',instructions:''});
 const [result,setResult]=useState<{job:ContentJob;text:string}>(),[error,setError]=useState(''),[opening,setOpening]=useState(false),[ack,setAck]=useState<string>(),[inspect,setInspect]=useState<string>();
 useEffect(()=>{saveLocal(key,draft);},[key,draft]);
 const source={contentId:entity.id,expectedRevision:entity.revision},jobs=state?.jobs??[];
 const chooseMode=(mode:ContentMode)=>{const role=mode==='review'?'review':mode==='research'?'research':'maker';setDraft({...draft,mode,agentId:agents.find(a=>a.value.position.toLowerCase().includes(role))?.id??draft.agentId});};
 const jobResult=async(id:string)=>{setOpening(true);setError('');try{setResult(await request(`content/result?id=${id}`));}catch(e){setError(e instanceof Error?e.message:'The result is unavailable.');}finally{setOpening(false);}};
 const selected=jobs.find(j=>j.id===result?.job.id)??result?.job,stale=selected&&selected.sourceRevision!==entity.revision;
 return <section className="content-agent-work"><h3>Work with your agents</h3><div className="content-mode-buttons" aria-label="Content agent action">{contentModes.map(mode=><button key={mode} aria-pressed={draft.mode===mode} onClick={()=>chooseMode(mode)}>{mode[0].toUpperCase()+mode.slice(1)}</button>)}</div>
 <label>Agent<select value={draft.agentId} onChange={e=>setDraft({...draft,agentId:e.target.value})}>{!agents.length&&<option value="">Create an agent first</option>}{agents.map(a=><option key={a.id} value={a.id}>{a.value.name} · {a.value.position}</option>)}</select></label><label>Directions <small>(optional)</small><textarea maxLength={6000} rows={3} value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})} placeholder="What should this run focus on?"/></label><button className="primary" disabled={blocked||!state?.canStart||!agents.some(a=>a.id===draft.agentId)} onClick={()=>void run({type:'work',...source,...draft})}>{draft.mode[0].toUpperCase()+draft.mode.slice(1)} version {entity.revision}</button>
 <p className="metadata">The selected agent uses this saved version, text sources and brand guidance. Improve also uses unresolved comments on this version. PDF pages and PNG, JPEG or WebP images can be inspected when needed. Check saved inputs for the pages and views read. The response stays separate until you apply it.</p>{!state?.canStart&&<p role="status" className="metadata">{state?.reason??'Connecting to the worker…'}</p>}
 {error&&<p role="alert" className="field-error">{error}</p>}
 <div className="content-jobs">{jobs.map(job=>{const a=job.attempt,active=a&&assignmentHoldsSlot(a);return <article key={job.id}><header><strong>{job.mode[0].toUpperCase()+job.mode.slice(1)} · {job.agentName}</strong><span>{job.appliedRevision?`Applied as v${job.appliedRevision}`:a?.state==='returned'?'Ready to review':a?.state??'Not started'}</span></header><p className="metadata">Source v{job.sourceRevision} · {new Date(job.createdAt).toLocaleString()}{job.brand?` · ${job.brand.name} v${job.brand.revision}`:''}{job.reviewContext?.length?` · ${job.reviewContext.reduce((n,r)=>n+r.comments.length,0)} review comments captured`:''}</p>{(job.error||a?.message)&&<p>{job.error??a?.message}</p>}<div className="button-row">{a&&<button onClick={()=>setInspect(a.id)}>Review saved inputs</button>}{a?.result&&<><button disabled={opening} onClick={()=>void jobResult(job.id)}>Compare result</button><a href={`/api/attachments/${a.result.file.id}`} download>Download response</a></>}{!a&&<button disabled={blocked||!state?.canStart} onClick={()=>void run({type:'work-control',jobId:job.id,action:'start'})}>Retry original run</button>}{active&&<><button disabled={blocked} onClick={()=>void run({type:'work-control',jobId:job.id,action:'check'})}>Check status</button><button disabled={blocked} onClick={()=>void run({type:'work-control',jobId:job.id,action:'stop'})}>Stop run</button>{a.stopReason&&['unknown','stopping'].includes(a.state)&&<button disabled={blocked} onClick={()=>setAck(job.id)}>Review unresolved run</button>}</>}</div>{ack===job.id&&<div className="notice"><p>The original outcome remains unknown. Another run may repeat work.</p><button disabled={blocked} onClick={async()=>{await run({type:'work-control',jobId:job.id,action:'acknowledge'});setAck(undefined);}}>Keep unresolved and allow another run</button><button onClick={()=>setAck(undefined)}>Keep waiting</button></div>}</article>;})}</div>
 {result&&selected&&<section className="content-result-comparison"><div className="section-heading"><h3>{selected.agentName} · {selected.mode} result</h3><button onClick={()=>setResult(undefined)}>Close result</button></div>{stale&&!selected.appliedRevision&&<p className="notice">Your draft has changed since this run. The original response is kept for comparison; start another run to work from the current version.</p>}<div className="content-comparison"><section><h4>Current draft · v{entity.revision}</h4><Suspense fallback={<pre>{entity.value.body}</pre>}><Preview value={entity.value}/></Suspense></section><section><h4>Agent proposal · source v{selected.sourceRevision}</h4><Suspense fallback={<pre>{result.text}</pre>}><Preview value={{...entity.value,body:result.text,format:'markdown'}}/></Suspense></section></div><div className="button-row">{selected.mode==='review'?<button disabled={blocked} onClick={async()=>{let review=state?.reviews.find(r=>r.sourceRevision===selected.sourceRevision&&r.reviewerId===selected.agentId);if(!review){if(stale){setError('Request a review for the current version. This older response remains available to download.');return;}review=await run({type:'review-request',...source,reviewerId:selected.agentId});}if(review)await run({type:'review-comment',...source,reviewId:review.id,reviewRevision:review.revision,text:'Agent review feedback',quote:'',jobId:selected.id});}}>Add feedback to review</button>:<><button className="primary" disabled={blocked||stale||!!selected.appliedRevision} onClick={()=>void run({type:'apply-work',...source,jobId:selected.id,placement:'replace'})}>Use as next draft version</button><button disabled={blocked||stale||!!selected.appliedRevision} onClick={()=>void run({type:'apply-work',...source,jobId:selected.id,placement:'append'})}>Append to draft</button></>}</div></section>}
 {inspect&&<Suspense fallback={<p role="status">Opening saved inputs…</p>}><Inputs id={inspect} close={()=>setInspect(undefined)}/></Suspense>}
 </section>;
}
