import {useEffect,useRef,useState} from 'react';
import type {Entity,Snapshot,Task} from '../../../packages/domain/contracts';
import {blankRecord,contentSchema,contentStages,type Content,type ContentOutputSource,type RecordValue} from '../../../packages/domain/workspace-records';
import {dayInZone} from '../../../packages/domain/tasks';
import {useRetained} from './useWorkspace';
import {Conflict} from './ui';
import {ContentWriting} from './ContentWriting';
import {ContentFiles} from './ContentFiles';
import {ContentTiming} from './ContentTiming';
import {ContentLibrary} from './ContentLibrary';
import {ContentReviews} from './ContentReviews';
import {ContentAgentWork} from './ContentAgentWork';
import {ContentVersions} from './ContentVersions';
import {RecordConnections} from './RecordConnections';
import {useContentCommand,useContentState,useContentLibrary} from './useContentWorkspace';
import {exportContent} from './record-files';
import {readLocal,saveLocal} from './api';
import './content-workspace.css';

export function ContentTagsInput({value,onChange}:{value:string[];onChange:(tags:string[])=>void}){
 const [raw,setRaw]=useState(value.join(', ')),known=useRef(JSON.stringify(value));
 useEffect(()=>{const encoded=JSON.stringify(value);if(encoded!==known.current){known.current=encoded;setRaw(value.join(', '));}},[value]);
 return <input maxLength={1000} value={raw} placeholder="Separate tags with commas" onChange={e=>{setRaw(e.target.value);const tags=[...new Set(e.target.value.split(',').map(t=>t.trim()).filter(Boolean))].slice(0,20);known.current=JSON.stringify(tags);onChange(tags);}}/>;
}
export default function ContentEditor({id,entity,snapshot,refresh,editTask,close,removeDraft,openSource,openAssistantSettings,requestPublication}:{id:string;entity?:Entity<Content>;snapshot:Snapshot;refresh:()=>Promise<void>;editTask:(t:Entity<Task>)=>void;close:()=>void;removeDraft:()=>void;openSource:(s:ContentOutputSource)=>void;openAssistantSettings?:()=>void;requestPublication?:string}){
 const [initial]=useState(()=>blankRecord('content',snapshot.layout.value.timezone) as Content),editor=useRetained<Content>('content',id,initial,entity,snapshot,refresh,{autoSave:false});
 const tabKey=`e3:content-tab:${snapshot.deviceId}:${id}`, [tab,setTab]=useState<'write'|'agents'|'review'|'versions'>(()=>readLocal(tabKey)??'write'),[error,setError]=useState(''),[filesPending,setFilesPending]=useState(false),[librarySeed,setLibrarySeed]=useState<Content>(),[exporting,setExporting]=useState(false);
 const activity=useContentState(id,!!entity),library=useContentLibrary();
 const command=useContentCommand(snapshot,id,async()=>{await refresh();await activity.load();});
 const changed=(patch:Partial<Content>)=>editor.change(v=>({...v,...patch}));
 const isDirty=editor.dirty||!!editor.pending||!!editor.conflict||editor.saving||filesPending;
 const blocked=isDirty||command.busy||!!command.pending||!!entity?.value.archived;
 const requestSeen=useRef<string|undefined>(undefined);
 useEffect(()=>{saveLocal(tabKey,tab);},[tab,tabKey]);
 useEffect(()=>{if(requestPublication&&requestPublication!==requestSeen.current&&!editor.pending&&!editor.conflict){requestSeen.current=requestPublication;changed({stage:'published',publication:editor.value.publication??{kind:'manual',date:dayInZone(snapshot.layout.value.timezone),note:''}});setTab('write');}},[requestPublication]);
 const save=async()=>{if(filesPending)return;const parsed=contentSchema.safeParse(editor.value);if(!parsed.success){setError(parsed.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join(' '));return;}editor.change(parsed.data);setError('');await editor.flush();};
 const exportPackage=async()=>{if(!entity)return;setExporting(true);setError('');try{const response=await fetch(`/api/content/package?id=${encodeURIComponent(id)}&revision=${entity.revision}`,{credentials:'same-origin'});if(!response.ok){const error=await response.json();throw new Error(error.message??'Export failed.');}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(entity.value.title.replace(/[^\p{L}\p{N}._-]+/gu,'-').slice(0,100)||'content')+`-v${entity.revision}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'The export could not finish.');}finally{setExporting(false);}};
 const currentReviews=activity.state?.reviews.filter(r=>r.sourceRevision===entity?.revision)??[],approved=currentReviews.length>0&&currentReviews.every(r=>r.state==='approved'&&!r.comments.some(c=>!c.resolved));
 const selectTab=(next:typeof tab)=>setTab(next);
 const value=editor.value;
 return <section className="card content-studio" aria-label="Content editor"><header className="content-studio-header"><div className="content-studio-identity"><span className="metadata">{entity?`Version ${entity.revision}`:'New Content'} · <span role="status">{editor.status}{approved&&!editor.dirty?' · Approved':''}</span></span>{tab==='write'?<label className="content-title-field"><span className="sr-only">Title</span><input required maxLength={300} placeholder="Untitled draft" value={value.title} disabled={editor.saving||!!editor.pending||value.archived||command.busy||!!command.pending} onChange={e=>changed({title:e.target.value})}/></label>:<h2>{value.title||'Untitled draft'}</h2>}</div><div className="content-studio-actions"><button onClick={close}>Keep & close</button>{(editor.dirty||!entity)&&<button disabled={editor.saving||!!editor.pending||command.busy||filesPending} onClick={()=>{editor.discard();setError('');if(!entity)removeDraft();}}>{entity?'Discard edits':'Discard draft'}</button>}<button className="primary" disabled={!editor.dirty||editor.saving||filesPending||!!editor.conflict||command.busy||!!command.pending||value.archived} onClick={()=>void save()}>{editor.pending?'Reconcile save':'Save version'}</button></div></header>
 <nav className="content-studio-tabs" aria-label="Content workspace">{([['write','Write'],['agents','Agent work'],['review','Review'],['versions','Versions']] as const).map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} disabled={!entity&&key!=='write'} onClick={()=>selectTab(key)}>{label}{key==='agents'&&activity.state?.jobs.some(j=>j.attempt?.state==='running')?' · Working':''}{key==='review'&&approved?' · Approved':''}</button>)}</nav>
 {(error||command.error||activity.error||library.error)&&<p role="alert" className="field-error">{error||command.error||activity.error||library.error}</p>}
 {command.pending&&!command.busy&&<div className="notice"><p>A Content change needs confirmation from the host.</p><button disabled={command.busy} onClick={()=>void command.run(command.pending!)}>Check original change</button></div>}
 {editor.conflict&&<Conflict name={value.title||'Content'} message={editor.conflict.message} current={editor.conflict.current?JSON.stringify(editor.conflict.current.value,null,2):undefined} reapply={editor.editProposal} reapplyLabel="Review my edits" discard={()=>editor.discard()}/>}
 {tab!=='write'&&isDirty&&<p className="notice">Save or discard your edits before acting on a saved version.</p>}
 {tab==='write'?<><fieldset disabled={editor.saving||!!editor.pending||value.archived||command.busy||!!command.pending}><ContentWriting value={value} change={changed}/>
 <details className="content-details" open={!!requestPublication||undefined}><summary>Brief & planning</summary><label>Brief<textarea rows={3} maxLength={10000} value={value.brief} onChange={e=>changed({brief:e.target.value})} placeholder="Who is this for, and what should it accomplish?"/></label><div className="record-field-grid"><label>Stage<select value={value.stage} onChange={e=>{const stage=e.target.value as Content['stage'];changed({stage,publication:stage==='published'?value.publication??{kind:'manual',date:dayInZone(snapshot.layout.value.timezone),note:''}:value.publication});}}>{contentStages.map(s=><option key={s}>{s}</option>)}</select></label><label>Platform or content type<input maxLength={100} required value={value.platform} onChange={e=>changed({platform:e.target.value})}/></label><label>Collection<input list={`collections-${id}`} maxLength={100} value={value.collection??''} onChange={e=>changed({collection:e.target.value})}/><datalist id={`collections-${id}`}>{[...new Set((snapshot.records?.content??[]).map(c=>c.value.collection).filter(Boolean))].map(c=><option key={c}>{c}</option>)}</datalist></label><label>Tags<ContentTagsInput value={value.tags??[]} onChange={tags=>changed({tags})}/></label><label>Project<select value={value.projectId??''} onChange={e=>changed({projectId:e.target.value||null})}><option value="">No Project</option>{snapshot.projects.map(p=><option key={p.id} value={p.id}>{p.value.name}</option>)}</select></label><label>Brand guidance<select value={value.brandId??''} onChange={e=>changed({brandId:e.target.value||null})}><option value="">No brand</option>{library.items.filter(b=>b.type==='brand'&&(!b.archived||b.id===value.brandId)).map(b=><option key={b.id} value={b.id}>{b.name} · v{b.revision}{b.archived?' · archived':''}</option>)}</select></label><label>Format<select value={value.format} onChange={e=>changed({format:e.target.value as Content['format']})}><option value="markdown">Markdown</option><option value="text">Plain text</option></select></label><label>Planned date<input type="date" value={value.plannedDate} onChange={e=>changed({plannedDate:e.target.value,...(!e.target.value?{plannedTime:'',plannedOverlap:undefined}:{})})}/></label></div><ContentTiming value={value} change={changed} timezone={snapshot.layout.value.timezone}/>{value.stage==='published'&&value.publication&&<section><h3>Manual publication record</h3><p className="metadata">Record where you already published this work. Saving does not publish it.</p><label>Published date<input type="date" required value={value.publication.date} onChange={e=>changed({publication:{...value.publication!,date:e.target.value}})}/></label><label>Where it was published<textarea required maxLength={2000} value={value.publication.note} onChange={e=>changed({publication:{...value.publication!,note:e.target.value}})}/></label></section>}</details>
 <details className="content-details"><summary>Files & images · {value.assets?.length??0}</summary><ContentFiles id={id} value={value} snapshot={snapshot} change={update=>editor.change(v=>update(v) as Content)} pendingChanged={setFilesPending}/><div className="content-image-gallery">{(value.assets??[]).filter(f=>/\.(png|jpe?g|webp)$/i.test(f.name)).map(file=><figure key={file.id}><img src={`/api/attachments/${file.id}?preview=1`} alt={file.name} loading="lazy"/><figcaption>{file.name}</figcaption>{value.format==='markdown'&&<button type="button" onClick={()=>changed({body:value.body+`\n\n![${file.name.replace(/[\[\]]/g,'')}](/api/attachments/${file.id})\n`})}>Insert into draft</button>}</figure>)}</div></details></fieldset>
 {entity&&<details className="content-details"><summary>Linked work & source</summary><RecordConnections kind="content" entity={entity} snapshot={snapshot} refresh={refresh} editTask={editTask} openSource={openSource}/></details>}</>:entity&&tab==='agents'?<ContentAgentWork entity={entity} snapshot={snapshot} state={activity.state} blocked={blocked} blockedReason={value.archived?'Restore this Content item before starting agent work.':command.busy?'A Content change is in progress.':command.pending?'Check the original Content change before starting.':'Save or discard your edits before starting from this version.'} run={command.run} openSettings={openAssistantSettings}/>:entity&&tab==='review'?<ContentReviews entity={entity} snapshot={snapshot} reviews={activity.state?.reviews??[]} blocked={blocked} run={command.run}/>:entity&&tab==='versions'?<ContentVersions entity={entity} blocked={blocked} run={command.run}/>:null}
 {entity&&<footer className="content-delivery"><div className="button-row"><button disabled={isDirty||command.busy||!!command.pending||exporting} onClick={()=>void exportPackage()}>{exporting?'Preparing package…':'Export draft & assets'}</button><button disabled={isDirty||command.busy||!!command.pending} onClick={()=>exportContent(entity.value,entity.revision)}>Export text</button><button disabled={isDirty||command.busy} onClick={()=>setLibrarySeed(entity.value)}>Save as template</button><button disabled={isDirty||command.busy} onClick={async()=>{editor.change(v=>({...v,archived:!v.archived}));await editor.flush();}}>{value.archived?'Restore Content':'Archive Content'}</button></div><small>Exports use saved version {entity.revision}. ZIP includes the exact draft, attached files, sources and review record.</small></footer>}
 {librarySeed&&<ContentLibrary snapshot={snapshot} seed={librarySeed} close={()=>{setLibrarySeed(undefined);void library.load();}}/>}
 </section>;
}
