import {useEffect,useState} from 'react';
import type {Snapshot,Entity} from '../../../packages/domain/contracts';
import type {Content} from '../../../packages/domain/workspace-records';
import type {ContentReview} from '../../../packages/domain/content-workspace';
import {readLocal,saveLocal} from './api';
export function ContentReviews({entity,snapshot,reviews,blocked,run}:{entity:Entity<Content>;snapshot:Snapshot;reviews:ContentReview[];blocked:boolean;run:(input:Record<string,unknown>)=>Promise<any>}){
 const key=`e3:content-review-draft:${snapshot.deviceId}:${snapshot.epoch}:${entity.id}`;
 const [draft,setDraft]=useState(()=>readLocal<{text:string;quote:string;note:string;reviewer:string}>(key)??{text:'',quote:'',note:'',reviewer:''}),[selected,setSelected]=useState('');
 useEffect(()=>{saveLocal(key,draft);},[key,draft]);
 const review=reviews.find(r=>r.id===selected)??reviews[0],stale=review&&review.sourceRevision!==entity.revision,source={contentId:entity.id,expectedRevision:entity.revision};
 const base=review?{...source,reviewId:review.id,reviewRevision:review.revision}:source;
 const decide=async(decision:'changes'|'approved')=>{const result=await run({type:'review-decide',...base,decision,note:draft.note});if(result)setDraft({...draft,note:''});};
 const current=reviews.filter(r=>r.sourceRevision===entity.revision),approved=current.length>0&&current.every(r=>r.state==='approved'&&!r.comments.some(c=>!c.resolved));
 return <section className="content-review-panel"><h3>{approved?`Version ${entity.revision} approved`:`Review version ${entity.revision}`}</h3><p className="metadata">Decisions belong to the reviewed version. New edits require a new review. Agent feedback is advisory; you make the final decision.</p>
 <div className="button-row"><label>Reviewer<select value={draft.reviewer} onChange={e=>setDraft({...draft,reviewer:e.target.value})}><option value="">You</option>{(snapshot.records?.agent??[]).filter(a=>!a.value.archived).map(a=><option key={a.id} value={a.id}>{a.value.name} · {a.value.position}</option>)}</select></label><button disabled={blocked} onClick={async()=>{const result=await run({type:'review-request',...source,reviewerId:draft.reviewer||null});if(result)setSelected(result.id);}}>Request review</button></div>
 {!!reviews.length&&<><label>Review history<select value={review?.id??''} onChange={e=>setSelected(e.target.value)}>{reviews.map(r=><option key={r.id} value={r.id}>Version {r.sourceRevision} · {r.reviewerName} · {r.state==='changes'?'Changes requested':r.state}</option>)}</select></label>{review&&<><div className="content-review-status"><strong>{review.reviewerName} · version {review.sourceRevision}</strong><span>{review.state==='changes'?'Changes requested':review.state==='approved'?'Approved by you':'Awaiting review'}{stale?' · Earlier version':''}</span></div>
 {review.comments.map(c=><article className={`content-comment${c.resolved?' resolved':''}`} key={c.id}><header><strong>{c.author}</strong><small>{new Date(c.at).toLocaleString()}</small></header>{c.quote&&<blockquote>{c.quote}</blockquote>}<p>{c.text}</p><button disabled={blocked} onClick={()=>void run({type:'review-resolve',...base,commentId:c.id,resolved:!c.resolved})}>{c.resolved?'Reopen comment':'Resolve comment'}</button></article>)}
 <label>Quoted passage <small>(optional)</small><textarea rows={2} maxLength={1000} value={draft.quote} onChange={e=>setDraft({...draft,quote:e.target.value})}/></label><label>Feedback<textarea rows={4} maxLength={10000} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><button disabled={blocked||!draft.text.trim()} onClick={async()=>{const result=await run({type:'review-comment',...base,text:draft.text,quote:draft.quote});if(result)setDraft({...draft,text:'',quote:''});}}>Add comment</button>
 <div className="content-review-decision"><label>Decision note <small>(optional)</small><textarea rows={2} maxLength={10000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><div className="button-row"><button disabled={blocked||stale} onClick={()=>void decide('changes')}>Request changes</button><button className="primary" disabled={blocked||stale||review.comments.some(c=>!c.resolved)} onClick={()=>void decide('approved')}>Approve version {review.sourceRevision}</button></div>{review.comments.some(c=>!c.resolved)&&<p className="metadata">Resolve open comments before approval.</p>}</div></>}</>}
 </section>;
}
