import { Suspense, useEffect, useState } from 'react';
import { lazy } from './preload-lazy';
import type {Content} from '../../../packages/domain/workspace-records';
import type {Entity} from '../../../packages/domain/contracts';
import {request} from './api';
import {exportContent} from './record-files';
const Preview=lazy(()=>import('./ContentPreview'));
export function ContentVersions({entity,blocked,run}:{entity:Entity<Content>;blocked:boolean;run:(input:Record<string,unknown>)=>Promise<any>}){
 const [versions,setVersions]=useState<Entity<Content>[]>([]),[cursor,setCursor]=useState<number|null>(null),[selected,setSelected]=useState<number>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async(before?:number)=>{setBusy(true);try{const result=await request<{versions:Entity<Content>[];beforeRevision:number|null}>('records/history',{kind:'content',id:entity.id,beforeRevision:before});setVersions(old=>before?[...old,...result.versions]:result.versions);setCursor(result.beforeRevision);setError('');}catch(e){setError(e instanceof Error?e.message:'History unavailable.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[entity.id,entity.revision]);
 const prior=versions.find(v=>v.revision===selected)??versions.find(v=>v.revision<entity.revision),lines=(text:string)=>text.split('\n');
 const before=lines(prior?.value.body??''),after=lines(entity.value.body);let start=0,end=0;while(start<Math.min(before.length,after.length)&&before[start]===after[start])start++;while(end<Math.min(before.length,after.length)-start&&before[before.length-1-end]===after[after.length-1-end])end++;
 return <section><h3>Version history</h3><p className="metadata">Compare saved writing and restore an earlier version as a new draft. Current and earlier versions remain in history.</p>{error&&<p role="alert">{error}</p>}<label>Compare with<select value={prior?.revision??''} onChange={e=>setSelected(Number(e.target.value))}><option value="">Choose a saved version</option>{versions.map(v=><option key={v.revision} value={v.revision}>Version {v.revision} · {new Date(v.updatedAt).toLocaleString()}</option>)}</select></label>{cursor&&<button disabled={busy} onClick={()=>void load(cursor)}>Load earlier versions</button>}{prior&&<><div className="content-version-stats">{prior.value.body===entity.value.body?'Writing is unchanged.':`Changed passage: ${Math.max(0,before.length-start-end)} earlier lines / ${Math.max(0,after.length-start-end)} current lines.`}</div><div className="content-comparison"><section><h4>Version {prior.revision}</h4><p>{prior.value.title}</p><p className="metadata">{prior.value.brief}</p><Suspense fallback={<pre>{prior.value.body}</pre>}><Preview value={prior.value}/></Suspense></section><section><h4>Current · version {entity.revision}</h4><p>{entity.value.title}</p><p className="metadata">{entity.value.brief}</p><Suspense fallback={<pre>{entity.value.body}</pre>}><Preview value={entity.value}/></Suspense></section></div>{prior.value.body!==entity.value.body&&<details><summary>Show changed source passage</summary><div className="content-comparison"><pre className="content-diff-before">{before.slice(start,before.length-end).join('\n')||'(No earlier text)'}</pre><pre className="content-diff-after">{after.slice(start,after.length-end).join('\n')||'(Text removed)'}</pre></div></details>}<div className="button-row"><button onClick={()=>exportContent(prior.value,prior.revision)}>Export version {prior.revision}</button><button className="primary" disabled={blocked||prior.revision===entity.revision} onClick={()=>void run({type:'restore',contentId:entity.id,expectedRevision:entity.revision,revision:prior.revision})}>Restore version {prior.revision} as new draft</button></div><p className="metadata">Restoring brings back its writing, organization and attached files. Publication is cleared and the restored draft needs a new review.</p></>}{!busy&&!prior&&<p className="metadata">Save another version to compare changes.</p>}</section>;
}
