import { groupVoiceMessages, transcriptContains, transcriptText } from './voice-transcript';
import { HistoryTool } from './ToolActivity';
import { ReplyText } from './ReplyText';
import { lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import type { Snapshot } from '../../../packages/domain/contracts';
import type { BrowseTarget } from '../../../packages/domain/search';
import type { ConversationHistory } from '../../../packages/domain/assistant';
import type { AssistantController } from './useAssistant';
import { request } from './api';
import { Archive, Download, PanelLeft, RotateCcw } from './icons';

const ContinueSavedConversation = lazy(() => import('./ContinueSavedConversation').then(module => ({ default: module.ContinueSavedConversation })));
export function ConversationReader({ target, snapshot, controller, close, change, sidebarControls, navigationCovered, refreshWorkspace }: { target: BrowseTarget; snapshot: Snapshot; controller: AssistantController; close: () => void; change: (target: BrowseTarget) => void; sidebarControls: ReactNode; navigationCovered: boolean; refreshWorkspace: () => Promise<void> }) {
  const conversation = controller.conversations.find(c => c.id === target.conversationId);
  const [history, setHistory] = useState<ConversationHistory>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0);
  const [continueSaved, setContinueSaved] = useState(false);
  const anchor = useRef<HTMLElement | null>(null);
  const currentTarget = useRef<BrowseTarget | null>(target); currentTarget.current = target;
  useEffect(() => { currentTarget.current = target; return () => { currentTarget.current = null; }; }, []);
  useEffect(() => {
    const abort = new AbortController(); let alive = true; setHistory(undefined); setError(''); setBusy(true);
    if (target.epoch !== snapshot.epoch) { setError('The workspace changed. Open this source from a current search.'); setBusy(false); return; }
    void request<ConversationHistory>('assistant/browse', target, abort.signal).then(value => { if (alive) setHistory(value); }).catch(reason => { if (alive && !abort.signal.aborted) setError(reason instanceof Error ? reason.message : 'This source is unavailable.'); }).finally(() => { if (alive) setBusy(false); });
    return () => { alive = false; abort.abort(); };
  }, [target, snapshot.epoch, controller.connection.generation, revision]);
  useEffect(() => { if (history && target.messageId) { anchor.current?.scrollIntoView({ block: 'center' }); anchor.current?.focus({ preventScroll: true }); } }, [history, target.messageId]);
  const restore = async () => { if (!conversation || busy) return; setBusy(true); setError(''); try { await controller.edit(conversation, conversation.deleted ? { deleted: false } : { archived: false }); } catch (reason) { if (currentTarget.current === target) setError(reason instanceof Error ? reason.message : 'The restore is not confirmed.'); } finally { if (currentTarget.current === target) setBusy(false); } };
  return <section className="conversation conversation-reader" aria-label="Read-only conversation" inert={navigationCovered}><div className="conversation-header">{sidebarControls}<div className="conversation-title"><span className="conversation-agent" aria-label="Chatting with Nova">Nova</span><strong>{conversation?.title ?? 'Saved conversation'}</strong><span>{snapshot.projects.find(p => p.id === conversation?.projectId)?.value.name ?? 'Unfiled'} · {conversation?.archived ? 'Archive · ' : ''}Read only</span></div><button onClick={close}>Back to writing</button></div>
    <div className="conversation-reading"><div className="reader-context"><p>{target.messageId ? 'Opened around the exact matching message.' : 'Reading saved history.'} Your writing, model and voice target stay in their original conversation.</p><button className="icon-button" aria-label="Refresh read-only history" disabled={busy} onClick={() => setRevision(n => n + 1)}><RotateCcw size={16}/></button></div>{error && <p className="notice warning" role="alert">{error}</p>}{busy && !history && <p role="status">Opening saved history…</p>}
    {history?.retained && <div className="history-status"><p>{history.retained.complete ? 'Showing the transcript saved at capture time.' : 'Showing only the captured portion of this conversation.'} Newer messages could not be checked.</p><button onClick={() => setContinueSaved(true)}>Continue in a fresh chat</button></div>}
    {continueSaved && <Suspense fallback={<p role="status">Opening saved transcript…</p>}><ContinueSavedConversation key={target.conversationId} conversationId={target.conversationId} snapshot={snapshot} controller={controller} refreshWorkspace={refreshWorkspace} prepared={close} close={() => setContinueSaved(false)}/></Suspense>}
    {history && <div className="chat-transcript" aria-label="Read-only messages">{history.hasMore && history.nextOffset !== undefined && !target.messageId && <button onClick={() => change({ ...target, offset: history.nextOffset })}>Earlier messages</button>}{(target.messageId || target.offset !== undefined) && <button onClick={() => conversation?.nativeId && change({ epoch: snapshot.epoch, conversationId: conversation.id, nativeId: conversation.nativeId })}>Latest messages</button>}
    {groupVoiceMessages(history.messages).map((message, index) => { const matched = !!target.messageId && transcriptContains(message, target.messageId, target.role ?? message.role); const files = controller.outputs.filter(o => o.state === 'ready' && o.conversationId === target.conversationId && o.nativeId === history.nativeId && o.messageId === message.id && o.messageHash === message.textHash); return <article aria-label={`${message.role} message`} key={JSON.stringify([message.id, message.sequence, message.role, index])} ref={matched && (!target.role || message.role === target.role) ? node => { if (node && (!anchor.current || !anchor.current.isConnected)) anchor.current = node; } : undefined} tabIndex={matched ? -1 : undefined} className={`chat-message message-${message.role} ${matched ? 'matched-message' : ''} ${message.toolInfo && (message.role === 'tool' || !message.text.trim()) ? 'message-tool-compact' : ''}`} data-message-id={message.id}>{(matched || message.role === 'tool' && !message.toolInfo || message.role === 'system') && <div className="message-author">{message.role === 'tool' ? 'Tool activity' : message.role === 'system' ? 'Conversation note' : null}{matched && <span className="match-label">{target.messageHash ? 'Source message' : 'Search match'}</span>}</div>}<HistoryTool message={message}/>{message.role !== 'tool' && <ReplyText text={transcriptText(message)} role={message.role}/>}{message.attachments.map((file, i) => <span className="source-link" key={`${file.artifactId}:${i}`}>{file.name}</span>)}{files.map(file => file.file && <a className="output-download" key={file.id} href={`/api/attachments/${file.file.id}`}><Download size={16}/>{file.name} · v{file.version}</a>)}</article>; })}{!history.messages.length && <p className="metadata">This conversation has no saved messages in this page.</p>}</div>}</div>
    <div className="archive-footer"><Archive size={19}/><span>{conversation?.archived ? 'Archive · reading does not restore this conversation.' : 'Read-only view · your active draft is kept.'}</span>{conversation?.pendingSettings ? <button disabled={busy} onClick={() => void controller.checkStatus(conversation.id).then(confirmed => { if (currentTarget.current !== target) return; if (confirmed) setRevision(n => n + 1); else setError('The host could not confirm this change. Keep it pending and check again.'); })}>Check original change</button> : conversation?.archived ? <button disabled={busy} onClick={() => void restore()}>Restore conversation</button> : conversation && conversation.nativeId === target.nativeId && <button onClick={() => { close(); controller.select(conversation.id); }}>Continue conversation</button>}</div>
  </section>;
}
