import { withQuestionReceipts } from './question-transcript';
import { QuestionReceipts } from './QuestionReceipts';
import { LoadingRing } from './ModuleLoading';
import { groupVoiceMessages, transcriptContains, transcriptText } from './voice-transcript';
import { HistoryTool } from './ToolActivity';
import { WorkTranscript } from './WorkTranscript';
import { groupWorkMessages } from './work-transcript';
import { SavedMessageText } from './ReplyText';
import { Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import { lazy } from './preload-lazy';
import type { Snapshot } from '../../../packages/domain/contracts';
import type { BrowseTarget } from '../../../packages/domain/search';
import type { ConversationHistory, ConversationMessage } from '../../../packages/domain/assistant';
import type { AssistantController } from './useAssistant';
import { request } from './api';
import { Archive, Download, PanelLeft, RotateCcw } from './icons';
import { browseTargetIdentity, matchesBrowseSource, retainedBrowseHistory, type BrowsedHistory } from './conversation-reader-state';

const ContinueSavedConversation = lazy(() => import('./ContinueSavedConversation').then(module => ({ default: module.ContinueSavedConversation })));
export function ConversationReader({ target, snapshot, controller, close, change, sidebarControls, navigationCovered, refreshWorkspace }: { target: BrowseTarget; snapshot: Snapshot; controller: AssistantController; close: () => void; change: (target: BrowseTarget) => void; sidebarControls: ReactNode; navigationCovered: boolean; refreshWorkspace: () => Promise<void> }) {
  const conversation = controller.conversations.find(c => c.id === target.conversationId);
  const [savedHistory, setSavedHistory] = useState<BrowsedHistory>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0);
  const targetIdentity = browseTargetIdentity(target);
  const history = retainedBrowseHistory(savedHistory, target, snapshot.epoch);
  const [continueSaved, setContinueSaved] = useState(false);
  const anchor = useRef<HTMLElement | null>(null);
  const currentTarget = useRef<BrowseTarget | null>(target); currentTarget.current = target;
  useEffect(() => { currentTarget.current = target; return () => { currentTarget.current = null; }; }, []);
  useEffect(() => {
    const abort = new AbortController(); let alive = true; setError(''); setBusy(true);
    if (target.epoch !== snapshot.epoch) { setError('The workspace changed. Open this source from a current search.'); setBusy(false); return; }
    void request<ConversationHistory>('assistant/browse', target, abort.signal).then(value => {
      if (!alive) return;
      if (!matchesBrowseSource(value, target)) throw Error('The returned history belongs to a different source. Open it from a current search.');
      setSavedHistory({ target, history: value });
    }).catch(reason => { if (alive && !abort.signal.aborted) setError(reason instanceof Error ? reason.message : 'This source is unavailable.'); }).finally(() => { if (alive) setBusy(false); });
    return () => { alive = false; abort.abort(); };
  }, [targetIdentity, snapshot.epoch, controller.connection.generation, revision]);
  useEffect(() => { if (!history || !target.messageId) return; const frame = requestAnimationFrame(() => { anchor.current?.scrollIntoView({ block: 'center' }); anchor.current?.focus({ preventScroll: true }); }); return () => cancelAnimationFrame(frame); }, [history, targetIdentity]);
  const restore = async () => { if (!conversation || busy) return; setBusy(true); setError(''); try { await controller.edit(conversation, conversation.deleted ? { deleted: false } : { archived: false }); } catch (reason) { if (currentTarget.current === target) setError(reason instanceof Error ? reason.message : 'The restore is not confirmed.'); } finally { if (currentTarget.current === target) setBusy(false); } };
  const renderMessage = (message: ConversationMessage, options?: { hideTool?: boolean }) => { const matched = !!target.messageId && transcriptContains(message, target.messageId, target.role ?? message.role); const nativeId = message.source?.nativeId ?? history!.nativeId; const ids = new Set([message.id, message.source?.nativeMessageId, ...(message.aliases ?? [])]); const files = controller.outputs.filter(o => o.state === 'ready' && o.conversationId === target.conversationId && o.nativeId === nativeId && ids.has(o.messageId) && o.messageHash === message.textHash); return <article aria-label={`${message.role} message`} key={`${message.role}:${message.novaId ?? message.id}`} ref={matched && (!target.role || message.role === target.role) ? node => { if (node) anchor.current = node; } : undefined} tabIndex={matched ? -1 : undefined} className={`chat-message message-${message.role} ${matched ? 'matched-message' : ''} ${message.toolInfo && (message.role === 'tool' || !message.text.trim()) ? 'message-tool-compact' : ''}`} data-message-id={message.id}>{(matched || message.role === 'tool' && !message.toolInfo || message.role === 'system') && <div className="message-author">{message.role === 'tool' ? 'Tool activity' : message.role === 'system' ? 'Conversation note' : null}{matched && <span className="match-label">{target.messageHash ? 'Source message' : 'Search match'}</span>}</div>}{!options?.hideTool && <HistoryTool message={message}/>}<SavedMessageText message={message} text={transcriptText(message)}/>{message.attachments.map((file, i) => file.localFile && file.availability !== 'unavailable' ? <a className="output-download" key={file.localFile.id} href={`/api/attachments/${file.localFile.id}`}><Download size={16}/>{file.name}</a> : <span className="source-link" key={`${file.artifactId}:${i}`}>{file.name}{file.availability === 'unavailable' ? ' · Unavailable' : ''}</span>)}{files.map(file => file.file && <a className="output-download" key={file.id} href={`/api/attachments/${file.file.id}`}><Download size={16}/>{file.name} · v{file.version}</a>)}</article>; };
  return <section className="conversation conversation-reader" aria-label="Read-only conversation" inert={navigationCovered}><div className="conversation-header">{sidebarControls}<div className="conversation-title"><span className="conversation-agent" aria-label="Chatting with Nova">Nova</span><strong>{conversation?.title ?? 'Saved conversation'}</strong><span>{snapshot.projects.find(p => p.id === conversation?.projectId)?.value.name ?? 'Unfiled'} · {conversation?.archived ? 'Archive · ' : ''}Read only</span></div><button onClick={close}>Back to writing</button></div>
    <div className="conversation-reading"><div className="reader-context"><p>{target.messageId ? 'Opened around the exact matching message.' : 'Reading saved history.'} Your writing, model and voice target stay in their original conversation.</p><button className="icon-button" aria-label="Refresh read-only history" disabled={busy} onClick={() => setRevision(n => n + 1)}><RotateCcw size={16}/></button></div>{error && <p className="notice warning" role="alert">{error}</p>}{busy && !history && <LoadingRing label="Opening saved history…"/>}
    {history?.retained && !history.retained.complete && <p className="metadata" role="status">Partial Saved Transcript</p>}
    {conversation && !conversation.archived && (conversation.pendingResume || history?.transcript?.bindingUnavailable || !!history?.messages.length && !!controller.connection.generation && conversation.connectionGeneration !== controller.connection.generation) && <div className="history-status"><span>Saved Chat · Current Connection Needed To Continue</span><button disabled={busy || controller.connection.state !== 'ready' || !controller.connection.modelAuthReady} onClick={() => setContinueSaved(true)}>Resume Chat</button></div>}
    {continueSaved && <Suspense fallback={<LoadingRing label="Opening saved transcript…"/>}><ContinueSavedConversation key={target.conversationId} conversationId={target.conversationId} snapshot={snapshot} controller={controller} refreshWorkspace={refreshWorkspace} prepared={close} close={() => setContinueSaved(false)}/></Suspense>}
    {history && <div className="chat-transcript" aria-label="Read-only messages">{history.hasMore && history.nextOffset !== undefined && !target.messageId && <button onClick={() => change({ ...target, offset: history.nextOffset })}>Earlier messages</button>}{(target.messageId || target.offset !== undefined) && <button onClick={() => conversation?.nativeId && change({ epoch: snapshot.epoch, conversationId: conversation.id, nativeId: conversation.nativeId })}>Latest messages</button>}
    {withQuestionReceipts(groupWorkMessages(groupVoiceMessages(history.messages), { operations: controller.operations, conversationId: target.conversationId, nativeId: history.nativeId }), { epoch: snapshot.epoch, conversationId: target.conversationId, operations: controller.operations, questions: controller.questions?.items, plans: controller.plans, history }).map(message => message.workParts ? <div key={`${message.role}:${message.novaId ?? message.id}`}><WorkTranscript message={message} renderMessage={renderMessage} onMatch={node => { if (node) anchor.current = node; }} match={target.messageId ? { id: target.messageId, role: target.role } : undefined}/></div> : <div key={`${message.role}:${message.novaId ?? message.id}`}><QuestionReceipts items={message.questionReceipts}/>{renderMessage(message)}<QuestionReceipts items={message.questionReceiptsAfter}/></div>)}{!history.messages.length && <p className="metadata">This conversation has no saved messages in this page.</p>}</div>}</div>
    <div className="archive-footer"><Archive size={19}/><span>{conversation?.archived ? 'Archive · reading does not restore this conversation.' : 'Read-only view · your active draft is kept.'}</span>{conversation?.pendingSettings ? <button disabled={busy} onClick={() => void controller.checkStatus(conversation.id).then(confirmed => { if (currentTarget.current !== target) return; if (confirmed) setRevision(n => n + 1); else setError('The host could not confirm this change. Keep it pending and check again.'); })}>Check original change</button> : conversation?.archived ? <button disabled={busy} onClick={() => void restore()}>{conversation.deleted ? 'Restore to Archive' : 'Restore conversation'}</button> : conversation && conversation.nativeId === target.nativeId && <button onClick={() => { close(); controller.select(conversation.id); }}>Continue conversation</button>}</div>
  </section>;
}
