import { useEffect, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Clock3, GripVertical, MoreHorizontal, Plus, Sparkles, Sun, X } from './icons';
import { statusNames } from '../../../packages/domain/tasks';
import { sizes, type Draft, type Entity, type Layout, type ModuleId, type Snapshot, type Task, type WidgetId } from '../../../packages/domain/contracts';
import { useReorder } from './useReorder';
import { Empty } from './ui';
import { homeTaskState, type HomeAttentionReason } from './home-task-state';

export const widgetNames: Record<WidgetId, string> = { welcome: 'Your day', next: 'Next work', draft: 'Continue a draft', attention: 'Attention', setup: 'Make yourself at home' };
const attentionLabels: Record<HomeAttentionReason, [string, string]> = { waiting: ['waiting task', 'waiting tasks'], blocked: ['blocked task', 'blocked tasks'], 'past-plan': ['missed plan', 'missed plans'], overdue: ['overdue deadline', 'overdue deadlines'] };
const nextEmptyCopy = {
  empty: { title: 'What would move today forward?', detail: 'Capture something small. You can give it a plan and a deadline later.', action: 'Add your first task' },
  future: { title: 'Your next tasks are planned for later', detail: 'Review All tasks to see your upcoming work, or capture something for today.', action: 'Add a task' },
  finished: { title: 'Your tasks are completed or skipped', detail: 'Show completed tasks to review them, or capture your next step.', action: 'Add a task' },
  'not-ready': { title: 'No tasks are ready right now', detail: 'Review All tasks for work that is planned for later, waiting, or blocked.', action: 'Add a task' },
};
export function Home({ snapshot, layout, saveLayout, open, openSettings, newTask, editTask, complete, draft, dirty, draftStatus }: { snapshot: Snapshot; layout: Layout; saveLayout: (value: Layout) => void; open: (id: ModuleId) => void; openSettings: (tab: 'general' | 'accounts') => void; newTask: () => void; editTask: (task: Entity<Task>) => void; complete: (task: Entity<Task>) => void; draft: Draft; dirty: boolean; draftStatus: string }) {
  const [menu, setMenu] = useState<WidgetId | null>(null);
  const [catalog, setCatalog] = useState(false);
  const [clock, setClock] = useState(Date.now());
  // Minute updates are enough for this date/time widget.
  useEffect(() => { const id = window.setInterval(() => setClock(Date.now()), 60000); return () => clearInterval(id); }, []);
  const reorder = useReorder(layout.widgets.filter(w => !w.hidden).map(w => w.id), order => {
    const hidden = layout.widgets.filter(w => w.hidden);
    saveLayout({ ...layout, widgets: [...order.map(id => layout.widgets.find(w => w.id === id)!), ...hidden] });
  }, 'widgets');
  const changeWidget = (id: WidgetId, values: Partial<Layout['widgets'][number]>) => saveLayout({ ...layout, widgets: layout.widgets.map(w => w.id === id ? { ...w, ...values } : w) });
  const date = new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric', timeZone: layout.timezone }).format(clock);
  const time = new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit', timeZone: layout.timezone }).format(clock);
  const { saved, active: activeTasks, tasks, completed, attention, emptyState } = homeTaskState(snapshot, layout, clock);
  const emptyCopy = nextEmptyCopy[emptyState];
  const attentionSummary = (Object.keys(attentionLabels) as HomeAttentionReason[]).flatMap(reason => {
    const count = attention.filter(item => item.reasons.includes(reason)).length;
    return count ? [`${count} ${attentionLabels[reason][count === 1 ? 0 : 1]}`] : [];
  }).join(' · ');
  const contents = (id: WidgetId) => {
    if (id === 'welcome') return <div className="welcome-content"><div><span className="eyebrow"><Sun size={16}/> A little space for your day</span><div className="clock">{time}</div><p>{date}</p><button className="text-button" onClick={() => openSettings('general')} title="Change timezone">{layout.timezone.replaceAll('_', ' ')} <ChevronDown size={14}/></button></div><img className="welcome-lynx" src="/mascot/lynx-welcome.webp" alt="Nova, ready to help" draggable={false}/></div>;
    if (id === 'next') return <><div className="widget-summary"><p>{activeTasks.length ? `${activeTasks.length} open ${activeTasks.length === 1 ? 'task' : 'tasks'} · ${completed} completed` : 'One clear next step is enough.'}</p><button className="icon-button" aria-label="Add a task" onClick={newTask}><Plus size={19}/></button></div>{tasks.length ? <div className="task-list">{tasks.map(task => <div className={`task-row ${task.value.status === 'done' ? 'completed' : ''}`} key={task.id}><button className={`check-button ${task.value.status === 'done' ? 'checked' : ''}`} aria-label={`${['done', 'skipped'].includes(task.value.status) ? 'Reopen' : 'Complete'} ${task.value.title}`} onClick={() => complete(task)}>{task.value.status === 'done' && <Check size={15}/>}</button><button className="task-open" onClick={() => editTask(task)}><strong>{task.value.title}</strong><span>{`${statusNames[task.value.status]}${task.value.planned ? ` · Planned ${task.value.planned}` : ''}`}{task.value.due ? ` · Due ${task.value.due}` : ''}</span></button></div>)}</div> : <Empty title={emptyCopy.title} action={<button className="primary" onClick={newTask}><Plus size={17}/>{emptyCopy.action}</button>}>{emptyCopy.detail}</Empty>}<button className="widget-link" onClick={() => open('tasks')}>All tasks <ArrowRight size={16}/></button></>;
    if (id === 'draft') return <div className="draft-widget"><div className="soft-icon violet"><Sparkles size={23}/></div><h3>{draft.text || draft.attachments.length ? draft.title : 'Room for your next thought'}</h3><p className="draft-excerpt">{draft.text || 'Start a conversation draft. Your words and attachments will be here when you return.'}</p>{draft.attachments.length > 0 && <p className="metadata">{draft.attachments.length} saved {draft.attachments.length === 1 ? 'attachment' : 'attachments'}</p>}{dirty && <span className="save-label pending">{draftStatus}</span>}<button className="widget-link" onClick={() => open('assistant')}>{draft.text ? 'Continue in Assistant' : 'Open Assistant'}<ArrowRight size={16}/></button></div>;
    if (id === 'attention') return <div className="attention-content"><div className="soft-icon green"><Check size={23}/></div><h3>{dirty ? 'A draft is still on this device' : attention.length ? `${attention.length} ${attention.length === 1 ? 'step needs' : 'steps need'} a fresh look` : 'No task needs intervention'}</h3>{(dirty || attention.length > 0) && <p>{dirty ? 'Open Assistant to check its save state.' : attentionSummary}</p>}{attention.length > 0 && <button className="widget-link" onClick={() => open('tasks')}>Review tasks<ArrowRight size={16}/></button>}{dirty && <button className="widget-link" onClick={() => open('assistant')}>Review draft<ArrowRight size={16}/></button>}</div>;
    return <div className="setup-content"><div><h3>A workspace that keeps your work.</h3><p>Start with a task, make the board yours, and keep a draft ready for your Assistant connection.</p></div><div className="setup-steps"><button onClick={newTask}><span className={`step-number ${saved.length ? 'done' : ''}`}>{saved.length ? <Check size={16}/> : '1'}</span><span>Capture your first task</span><ArrowRight size={16}/></button><button onClick={() => open('assistant')}><span className={`step-number ${draft.text ? 'done' : ''}`}>{draft.text ? <Check size={16}/> : '2'}</span><span>Keep a conversation draft</span><ArrowRight size={16}/></button><button onClick={() => openSettings('accounts')}><span className="step-number">3</span><span>Review connections</span><ArrowRight size={16}/></button></div></div>;
  };
  return <div className="home-page page-scroll" data-reorder-scroll><div className="page-intro"><div><h1>Today</h1></div><div className="catalog-wrap"><button onClick={() => setCatalog(!catalog)}><Plus size={17}/>Add widget</button>{catalog && <div className="popover catalog"><div className="section-heading"><strong>Home widgets</strong><button className="icon-button" aria-label="Close widget catalog" onClick={() => setCatalog(false)}><X size={17}/></button></div>{layout.widgets.map(widget => <button key={widget.id} onClick={() => changeWidget(widget.id, { hidden: !widget.hidden })}><span>{widgetNames[widget.id]}</span>{widget.hidden ? <Plus size={16}/> : <Check size={16}/>}</button>)}</div>}</div></div>
    <div className="home-grid">{reorder.order.map(id => { const widget = layout.widgets.find(w => w.id === id)!; return <section className={`widget widget-${id} size-${widget.size} ${reorder.dragging === id ? 'dragging' : ''}`} key={id} data-reorder-group="widgets" data-reorder-item={id} aria-label={widgetNames[id]}><div className="widget-header"><button className="widget-handle" {...reorder.bind(id)} onKeyDown={event => { if (event.altKey && ['ArrowUp', 'ArrowDown'].includes(event.key)) { event.preventDefault(); reorder.move(id, reorder.order.indexOf(id) + (event.key === 'ArrowUp' ? -1 : 1)); } }} aria-label={`${widgetNames[id]} widget. Drag to move or use Alt and arrow keys.`}><GripVertical size={14}/><span>{widgetNames[id]}</span></button><button className="icon-button" aria-label={`${widgetNames[id]} options`} aria-expanded={menu === id} onClick={() => setMenu(menu === id ? null : id)}><MoreHorizontal size={20}/></button></div>{menu === id && <div className="popover widget-options"><div className="section-heading"><strong>Widget options</strong><button className="icon-button" aria-label="Close widget options" onClick={() => setMenu(null)}><X size={16}/></button></div><span className="metadata">Size</span><div className="size-options">{sizes.map(size => <button key={size} aria-pressed={widget.size === size} onClick={() => changeWidget(id, { size })}>{size}</button>)}</div>{id === 'next' && <label className="check-label"><input type="checkbox" checked={layout.showCompleted} onChange={event => saveLayout({ ...layout, showCompleted: event.target.checked })}/>Show completed tasks</label>}{id === 'welcome' && <button onClick={() => openSettings('general')}><Clock3 size={16}/>Change timezone</button>}<button disabled={reorder.order.indexOf(id) === 0} onClick={() => reorder.move(id, reorder.order.indexOf(id) - 1)}>Move earlier</button><button disabled={reorder.order.indexOf(id) === reorder.order.length - 1} onClick={() => reorder.move(id, reorder.order.indexOf(id) + 1)}>Move later</button><button onClick={() => { changeWidget(id, { hidden: true }); setMenu(null); }}>Hide widget</button></div>}<div className="widget-body">{contents(id)}</div></section>; })}</div><p className="board-hint">Make this board yours. Drag a widget header, or use its options to move and resize it.</p><span className="sr-only" role="status">{reorder.announcement}</span>
  </div>;
}
