import { createRoot } from 'react-dom/client';
import './install';
import { applyDocumentAppIcon, readCachedAppIcon } from './app-icon';
import { initializeTypography } from './typography';
import '@fontsource-variable/sora';
import { App } from './App';
import './styles.css';
import './theme.css';
import './ui-refinements.css';
import './home.css';
import './home-widget-dialog.css';
import './home-appointment.css';
import './home-weather-visual.css';
import './home-widget-motion.css';
import './home-widget-colors.css';
import './buttons.css';
import './home-widget-controls.css';
import './app-icon.css';
import './voice-panel.css';
import './typography.css';

applyDocumentAppIcon(readCachedAppIcon());
initializeTypography();
createRoot(document.getElementById('root')!).render(<App/>);
