import { ContactOrganizations } from './ContactOrganizations';
import { ContentTiming } from './ContentTiming';
import { useState } from 'react';
import { X } from './icons';
import type { Snapshot } from '../../../packages/domain/contracts';
import { contactSchema, contentStages, type AgentDesign, type Assignment, type Contact, type Content, type PersonalProfile, type RecordKind, type RecordValue } from '../../../packages/domain/workspace-records';
import { dayInZone } from '../../../packages/domain/tasks';
import { PortraitPicker } from './PortraitPicker';
import { agentModules, type AgentAccess } from '../../../packages/domain/agent-capabilities';

function Field({ label, value, change, max = 240, rows, type = 'text', required = false }: { label: string; value: string; change: (value: string) => void; max?: number; rows?: number; type?: string; required?: boolean }) {
  return <label>{label}{rows ? <textarea rows={rows} maxLength={max} value={value} onChange={e => change(e.target.value)} required={required}/> : <input type={type} maxLength={max} value={value} onChange={e => change(e.target.value)} required={required}/>}</label>;
}

export function AgentAccessFields({ value, change }: { value: AgentAccess; change: (value: AgentAccess) => void }) {
  return <fieldset className="agent-access-fields"><legend>Workspace capabilities</legend><p className="metadata">Choose what this agent can read or edit. Removing access also restricts an attempt already running; added access applies to a new attempt.</p><div className="record-field-grid">{agentModules.map(module => <label key={module}>{module[0].toUpperCase() + module.slice(1)}<select aria-label={`${module} capability`} value={value[module] ?? 'none'} onChange={e => {
    const next = { ...value }; if (e.target.value === 'none') delete next[module]; else next[module] = e.target.value as 'read' | 'edit'; change(next);
  }}><option value="none">No access</option><option value="read">Read</option><option value="edit">Read & edit</option></select></label>)}</div></fieldset>;
}
function Tags({ value, change }: { value: string[]; change: (value: string[]) => void }) {
  const [draft, setDraft] = useState('');
  const add = () => { const tag = draft.trim(); if (tag && !value.includes(tag) && value.length < 30) { change([...value, tag]); setDraft(''); } };
  return <div className="record-tags"><label>Tags<div className="button-row"><input value={draft} maxLength={60} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); add(); } }} placeholder="Add a tag"/><button type="button" disabled={!draft.trim() || value.length >= 30} onClick={add}>Add</button></div></label><div className="button-row">{value.map(tag => <button type="button" key={tag} aria-label={`Remove tag ${tag}`} onClick={() => change(value.filter(t => t !== tag))}>{tag}<X size={14}/></button>)}</div></div>;
}
export function RecordFields({ kind, value, change, snapshot, agentStep }: { kind: RecordKind; value: RecordValue; change: (value: RecordValue) => void; snapshot: Snapshot; agentStep?: 'identity' | 'appearance' | 'work' }) {
  const project = (v: Contact | Content | Assignment) => <label>Project<select value={v.projectId ?? ''} onChange={e => change({ ...v, projectId: e.target.value || null })}><option value="">No Project</option>{snapshot.projects.map(p => <option key={p.id} value={p.id}>{p.value.name}</option>)}</select></label>;
  if (kind === 'contact') {
    const v = value as Contact; const set = (patch: Partial<Contact>) => change({ ...v, ...patch });
    return <><div className="record-field-grid"><Field label="Name" value={v.name} change={name => set({ name })} required/><ContactOrganizations value={v} change={set}/><Field label="Email" type="email" max={254} value={v.email} change={email => set({ email })}/><Field label="Phone" type="tel" max={80} value={v.phone} change={phone => set({ phone })}/></div><Field label="Private notes" rows={4} max={20000} value={v.notes} change={notes => set({ notes })}/><details className="contact-more-fields"><summary>More details</summary><div className="record-field-grid"><Field label="Position" value={v.position} change={position => set({ position })}/><Field label="Handle" value={v.handle} change={handle => set({ handle })}/><Field label="Timezone" value={v.timezone} change={timezone => set({ timezone })}/><label>Category<select value={v.category} onChange={e => set({ category: e.target.value as Contact['category'] })}>{['external', 'client', 'internal', 'content'].map(t => <option key={t}>{t}</option>)}</select></label>{project(v)}</div><ContactEmails value={v.otherEmails ?? []} change={otherEmails => set({ otherEmails })}/><Tags value={v.tags} change={tags => set({ tags })}/></details></>;

  }
  if (kind === 'content') {
    const v = value as Content; const set = (patch: Partial<Content>) => change({ ...v, ...patch });
    return <><Field label="Title" value={v.title} change={title => set({ title })} required/><div className="record-field-grid"><label>Stage<select value={v.stage} onChange={e => { const stage = e.target.value as Content['stage']; set({ stage, publication: stage === 'published' ? v.publication ?? { kind: 'manual', date: dayInZone(snapshot.layout?.value.timezone ?? 'UTC'), note: '' } : v.publication }); }}>{contentStages.map(stage => <option key={stage}>{stage}</option>)}</select></label><Field label="Platform" max={100} value={v.platform} change={platform => set({ platform })} required/>{project(v)}<Field label="Planned date" type="date" value={v.plannedDate} change={plannedDate => set({ plannedDate, ...(!plannedDate ? { plannedTime: '', plannedOverlap: undefined } : {}) })}/><label>Format<select value={v.format} onChange={e => set({ format: e.target.value as Content['format'] })}><option value="markdown">Markdown</option><option value="text">Plain text</option></select></label></div><ContentTiming value={v} change={set} timezone={snapshot.layout.value.timezone}/><Field label="Brief" rows={3} max={10000} value={v.brief} change={brief => set({ brief })}/><Field label="Draft" rows={14} max={100000} value={v.body} change={body => set({ body })}/>{v.stage === 'published' && v.publication && <section className="record-publication"><h3>Manual publication record</h3><p className="metadata">Record something you already published. Saving here does not send or publish this draft.</p><Field label="Published date" type="date" value={v.publication.date} change={date => set({ publication: { ...v.publication!, date } })} required/><Field label="Where it was published" rows={2} max={2000} value={v.publication.note} change={note => set({ publication: { ...v.publication!, note } })} required/></section>}</>;
  }
  if (kind === 'assignment') {
    const v = value as Assignment; const set = (patch: Partial<Assignment>) => change({ ...v, ...patch });
    const agents = snapshot.records?.agent ?? []; const current = agents.find(a => a.id === v.agentId);
    return <><p className="metadata">Save the plan, then start an attempt from its saved version below.</p><Field label="Title" value={v.title} change={title => set({ title })} required/><div className="record-field-grid"><label>Agent design<select required value={v.agentId} onChange={e => { const agent = agents.find(a => a.id === e.target.value); set({ agentId: agent?.id ?? '', agentRevision: agent?.revision ?? 1 }); }}><option value="">Choose an agent</option>{agents.filter(a => !a.value.archived || a.id === v.agentId).map(a => <option key={a.id} value={a.id}>{a.value.name}{a.value.archived ? ' · archived' : ''}</option>)}</select></label>{project(v)}<Field label="Due date" type="date" value={v.due} change={due => set({ due })}/><label>Plan status<select value={v.state} onChange={e => set({ state: e.target.value as Assignment['state'] })}><option value="planned">Planned</option><option value="cancelled">Cancelled</option></select></label></div>{current && current.revision !== v.agentRevision && <div className="notice"><span>This plan refers to design version {v.agentRevision}. The current design is version {current.revision}.</span><button type="button" disabled={current.value.archived} onClick={() => set({ agentRevision: current.revision })}>Use current design</button></div>}<Field label="Assignment brief" rows={5} max={20000} value={v.brief} change={brief => set({ brief })}/><Field label="Expected output" rows={4} max={10000} value={v.expectedOutput} change={expectedOutput => set({ expectedOutput })}/><label>Time before requesting stop<select value={v.maxMinutes ?? 5} onChange={e => set({ maxMinutes: Number(e.target.value) })}>{[1, 2, 3, 5, 10].map(minutes => <option key={minutes} value={minutes}>{minutes} minute{minutes === 1 ? "" : "s"}</option>)}</select></label><p className="metadata">The time limit includes waiting for approval. Choose enough time to review each action; it does not extend a tool’s access permission.</p><AssignmentSources value={v} change={set} snapshot={snapshot}/></>;
  }
  if (kind === 'agent') {
    const v = value as AgentDesign; const set = (patch: Partial<AgentDesign>) => change({ ...v, ...patch });
    return <>{(!agentStep || agentStep === 'identity') && <><div className="record-field-grid"><Field label="Name" value={v.name} change={name => set({ name })} required/><Field label="Position" value={v.position} change={position => set({ position })} required/></div><Field label="Purpose" rows={3} max={10000} value={v.purpose} change={purpose => set({ purpose })}/></>}{(!agentStep || agentStep === 'appearance') && <PortraitPicker name={v.name} value={v.appearance} change={appearance => set({ appearance })}/>} {(!agentStep || agentStep === 'work') && <><Field label="Instructions" rows={5} max={20000} value={v.instructions} change={instructions => set({ instructions })}/><Field label="Supplied knowledge" rows={4} max={20000} value={v.knowledge} change={knowledge => set({ knowledge })}/><Field label="Limits" rows={3} max={10000} value={v.nonGoals} change={nonGoals => set({ nonGoals })}/><Field label="Review criteria" rows={3} max={10000} value={v.reviewCriteria} change={reviewCriteria => set({ reviewCriteria })}/><p className="metadata">Assignments use this saved design and the capabilities you choose below. Host skill proposals can be reviewed separately in the skill library.</p></>}</>;
  }
  const v = value as PersonalProfile; const set = (patch: Partial<PersonalProfile>) => change({ ...v, ...patch });
  return <><div className="record-field-grid"><Field label="Name" value={v.name} change={name => set({ name })} required/><Field label="Position" value={v.position} change={position => set({ position })}/></div><PortraitPicker name={v.name} value={v.appearance} change={appearance => set({ appearance })}/><Field label="About you" rows={4} max={10000} value={v.about} change={about => set({ about })}/></>;
}

function AssignmentSources({ value, change, snapshot }: { value: Assignment; change: (patch: Partial<Assignment>) => void; snapshot: Snapshot }) {
  const selected = value.sources ?? [];
  const options = [...(snapshot.records?.content ?? []).map(record => ({ kind: 'content' as const, record })), ...(snapshot.records?.contact ?? []).map(record => ({ kind: 'contact' as const, record }))];
  return <section className="assignment-sources"><h3>Source records</h3><p className="metadata">Choose up to five saved Content drafts or Contacts. Their saved text and supported source files are included, together with the selected Project files. TXT, Markdown, CSV and JSON are read in full. Agents can inspect captured PDF pages and PNG, JPEG or WebP images through source tools; each binary file is limited to 8 MB.</p><label>Add a saved source<select value="" disabled={selected.length >= 5} onChange={event => { const item = options.find(option => option.record.id === event.target.value); if (item) change({ sources: [...selected, { kind: item.kind, id: item.record.id, revision: item.record.revision }] }); }}><option value="">Choose a source…</option>{options.filter(item => !item.record.value.archived && !selected.some(source => source.id === item.record.id)).map(item => <option key={item.record.id} value={item.record.id}>{'title' in item.record.value ? item.record.value.title : item.record.value.name} · {item.kind} v{item.record.revision}</option>)}</select></label>{selected.map(source => { const item = options.find(option => option.record.id === source.id && option.kind === source.kind); return <div key={source.id} className="assignment-source-row"><span>{item ? 'title' in item.record.value ? item.record.value.title : item.record.value.name : 'Unavailable source'} · saved version {source.revision}</span><div className="button-row">{item && item.record.revision !== source.revision && <button type="button" disabled={item.record.value.archived} onClick={() => change({ sources: selected.map(current => current.id === source.id ? { ...source, revision: item.record.revision } : current) })}>Use version {item.record.revision}</button>}<button type="button" onClick={() => change({ sources: selected.filter(current => current.id !== source.id) })}>Remove source</button></div></div>; })}</section>;
}

function ContactEmails({ value, change }: { value: string[]; change(value: string[]): void }) {
  const [draft, setDraft] = useState(''), [error, setError] = useState('');
  const add = () => { const email = draft.trim(); if (!email || !contactSchema.shape.email.safeParse(email).success) { setError('Enter a complete email address.'); return; } if (value.length >= 100) { setError('This contact already has 100 additional email addresses.'); return; } if (!value.includes(email)) change([...value, email]); setDraft(''); setError(''); };
  return <div className="contact-extra-emails">{error && <p role="alert" className="field-error">{error}</p>}<label>Other email addresses<div className="button-row"><input aria-label="Another email address" type="text" inputMode="email" maxLength={254} value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); add(); } }} placeholder="Add another email"/><button type="button" disabled={!draft.trim()} onClick={add}>Add</button></div></label><div className="button-row">{value.map(email => <button type="button" key={email} aria-label={`Remove email ${email}`} onClick={() => change(value.filter(item => item !== email))}>{email}<X size={14}/></button>)}</div></div>;
}
