import { ProjectOptions } from './ProjectOptions';
import { TaskFamily } from './TaskFamily';
import { SubtaskFields } from './SubtaskFields';
import { syncTaskSubtasks } from '../../../packages/domain/task-subtasks';
import { TaskHistory } from './TaskHistory';
import { useRef, useState } from 'react';
import { AlertCircle, Save, X } from './icons';
import type { Command, Entity, Snapshot, Task } from '../../../packages/domain/contracts';
import { ApiError, commit, readLocal, saveLocal } from './api';
import { dayInZone, nextDay, statusNames } from '../../../packages/domain/tasks';
import { Dialog } from './ui';

export function TaskEditor({ task, snapshot, close, saved, openOrigin, openTask, newTask }: { task: Entity<Task>; snapshot: Snapshot; close: () => void; saved: () => void; openTask?: (task: Entity<Task>) => void; newTask?: (defaults: Partial<Task>) => void; openOrigin?: (origin: NonNullable<Task['origin']>) => void }) {
  const key = `e3:task-editor:${snapshot.deviceId}:${task.id}`;
  const initial = task.value.trashed ? { value: task.value, revision: task.revision, epoch: snapshot.epoch, pending: undefined as Command | undefined } : readLocal<{ value: Task; revision: number; epoch: string; pending?: Command }>(key) ?? { value: task.value, revision: task.revision, epoch: snapshot.epoch };
  const [state, setState] = useState(initial); const ref = useRef(state);
  const [historyOpen, setHistoryOpen] = useState(false), [storageError, setStorageError] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [conflict, setConflict] = useState<Entity<Task> | null>(null); const [needsReview, setNeedsReview] = useState(false);
  const persist = (next: typeof state) => { ref.current = next; setState(next); const kept = saveLocal(key, next); setStorageError(!kept); if (!kept) setError('Browser storage is full. Keep this window open until your edits can be kept.'); return kept; };
  const change = (patch: Partial<Task>) => { persist({ ...ref.current, value: syncTaskSubtasks({ ...ref.current.value, ...patch }, ref.current.value) }); };
  const navigate = (action: () => void) => { if (task.value.trashed || persist(ref.current)) action(); else setError('Free browser storage before leaving. Your latest edits are still in this window.'); };
  const keepAndClose = () => navigate(close);
  const submit = async () => {
    if (busy || needsReview || task.value.trashed) return;
    const command = ref.current.pending ?? { requestId: crypto.randomUUID(), epoch: ref.current.epoch, kind: 'task' as const, entityId: task.id, expectedRevision: ref.current.revision, payload: ref.current.value };
    if (!saveLocal(key, { ...ref.current, pending: command })) { setError('Cannot preserve the save request in this browser. Free browser storage before trying again.'); return; }
    persist({ ...ref.current, pending: command }); setBusy(true); setError('');
    try { await commit(command); localStorage.removeItem(key); saved(); }
    catch (reason) {
      setError(reason instanceof Error ? reason.message : 'The host has not confirmed this save.');
      if (reason instanceof ApiError) {
        if (reason.code === 'revision_conflict' || reason.code === 'epoch_changed') { setNeedsReview(true); setConflict(reason.current as Entity<Task> ?? null); }
        else if (['validation', 'invalid_time', 'invalid_reminder_time', 'missing_project', 'invalid_dependency', 'dependency_open', 'checklist_open', 'invalid_occurrence', 'task_trashed', 'task_required', 'invalid_parent', 'task_has_children'].includes(reason.code)) persist({ ...ref.current, pending: undefined });
      }
    } finally { setBusy(false); }
  };
  return <Dialog title={task.revision ? 'Task details' : 'Capture a task'} close={keepAndClose}>{task.value.origin && openOrigin && <div className="notice"><span>Linked {task.value.origin.kind} · source version {task.value.origin.revision}</span><button type="button" onClick={() => navigate(() => openOrigin(task.value.origin!))}>Open source</button></div>}<form className="task-editor" onInvalid={event => { const field = event.target as HTMLElement; const section = field.closest('details'); if (section) section.open = true; }} onKeyDown={e => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); e.currentTarget.requestSubmit(); } }} onSubmit={event => { event.preventDefault(); void submit(); }}><fieldset disabled={busy || !!state.pending || !!task.value.trashed}><label>What needs doing?<input autoFocus value={state.value.title} required maxLength={300} onChange={event => change({ title: event.target.value })} placeholder="A clear next step"/></label><label>Notes<textarea rows={3} value={state.value.notes} maxLength={10000} onChange={event => change({ notes: event.target.value })} placeholder="Context, a useful link, or where to begin"/></label><div className="form-grid"><label>Planned for<input type="date" value={state.value.planned} onChange={event => change({ planned: event.target.value, plannedTime: event.target.value ? state.value.plannedTime : '' })}/><small>When you intend to work on it.</small></label><label>Due by<input type="date" value={state.value.due} onChange={event => change({ due: event.target.value, dueTime: event.target.value ? state.value.dueTime : '' })}/><small>The actual deadline, if there is one.</small></label></div><div className="task-date-shortcuts"><button type="button" onClick={() => change({ planned: dayInZone(snapshot.layout.value.timezone) })}>Today</button><button type="button" onClick={() => change({ planned: nextDay(dayInZone(snapshot.layout.value.timezone)) })}>Tomorrow</button><button type="button" onClick={() => change({ planned: '', plannedTime: '', bucket: 'anytime' })}>Anytime</button></div><SubtaskFields owner={task.id} value={state.value} change={change} snapshot={snapshot}/>
    <TaskFamily task={task} value={state.value} snapshot={snapshot} change={change} openTask={openTask ? next => navigate(() => openTask(next)) : undefined} newTask={newTask ? defaults => navigate(() => newTask(defaults)) : undefined}/><details className="task-more"><summary>Time, status & Project</summary><div className="task-detail-fields"><div className="form-grid"><label>Planned time<input type="time" disabled={!state.value.planned} value={state.value.plannedTime ?? ''} onChange={e => change({ plannedTime: e.target.value, timezone: state.value.timezone ?? snapshot.layout.value.timezone })}/></label><label>Deadline time<input type="time" disabled={!state.value.due} value={state.value.dueTime ?? ''} onChange={e => change({ dueTime: e.target.value, timezone: state.value.timezone ?? snapshot.layout.value.timezone })}/></label></div>
    <div className="form-grid"><label>Status<select value={state.value.status} onChange={event => change({ status: event.target.value as Task['status'] })}>{Object.entries(statusNames).filter(([status]) => status !== 'skipped' || snapshot.taskState?.occurrences.some(o => o.taskId === task.id)).map(([status, name]) => <option key={status} value={status}>{name}</option>)}</select></label><label>Priority<select value={state.value.priority ?? 'normal'} onChange={e => change({ priority: e.target.value as Task['priority'] })}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label></div>
    {(state.value.status === 'waiting' || state.value.status === 'blocked') && <label>What are you waiting on?<input maxLength={1000} value={state.value.waitReason ?? ''} onChange={e => change({ waitReason: e.target.value })} placeholder="The next checkpoint or missing prerequisite"/></label>}
    <div className="form-grid"><label>Project<select value={state.value.projectId ?? ''} onChange={e => change({ projectId: e.target.value || null })}><option value="">Personal</option><ProjectOptions snapshot={snapshot} selected={state.value.projectId}/></select></label><label>Estimate (minutes)<input type="number" min={0} max={1440} value={state.value.estimateMinutes || ''} onChange={e => change({ estimateMinutes: Number(e.target.value) })}/></label></div>
    {!state.value.planned && <label>Keep in<select value={state.value.bucket ?? 'capture'} onChange={e => change({ bucket: e.target.value as Task['bucket'] })}><option value="capture">Capture · plan later</option><option value="anytime">Anytime · ready without a date</option></select></label>}
<label>Timezone<select value={state.value.timezone ?? snapshot.layout.value.timezone} onChange={e => change({ timezone: e.target.value })}>{[...new Set([state.value.timezone ?? snapshot.layout.value.timezone, 'UTC', 'America/Los_Angeles', 'America/New_York', 'Europe/London', 'Asia/Tokyo'])].map(zone => <option key={zone}>{zone}</option>)}</select></label></div></details>    <details className="task-more"><summary>Reminder</summary><div className="task-detail-fields">{state.value.reminder ? <><div className="form-grid"><label>Reminder date<input required type="date" value={state.value.reminder.date} onChange={e => change({ reminder: { ...state.value.reminder!, date: e.target.value } })}/></label><label>Reminder time<input required type="time" value={state.value.reminder.time} onChange={e => change({ reminder: { ...state.value.reminder!, time: e.target.value } })}/></label></div><label>Reminder timezone<select value={state.value.reminder.timezone} onChange={e => change({ reminder: { ...state.value.reminder!, timezone: e.target.value } })}>{[...new Set([state.value.reminder.timezone, snapshot.layout.value.timezone, 'UTC', 'America/Los_Angeles', 'America/New_York', 'Europe/London', 'Asia/Tokyo'])].map(zone => <option key={zone}>{zone}</option>)}</select></label><label>If clocks repeat this time<select value={state.value.reminder.overlap ?? ''} onChange={e => change({ reminder: { ...state.value.reminder!, overlap: e.target.value as 'earlier' | 'later' || undefined } })}><option value="">Ask me to choose</option><option value="earlier">Earlier occurrence</option><option value="later">Later occurrence</option></select></label><button type="button" onClick={() => change({ reminder: null })}>Remove reminder</button></> : <button type="button" onClick={() => change({ reminder: { date: state.value.planned || dayInZone(snapshot.layout.value.timezone), time: state.value.plannedTime || '09:00', timezone: state.value.timezone || snapshot.layout.value.timezone } })}>Add a reminder</button>}<p className="metadata">Reminders are separate from the plan and deadline. The host keeps due alerts; device notifications need this app open and permission. Reopening a finished task does not silently rearm its old reminder.</p></div></details>
    <details className="task-more"><summary>Dependencies & source links</summary><div className="task-detail-fields">
    <label>Add a prerequisite<select value="" onChange={e => { if (e.target.value) change({ dependencies: [...(state.value.dependencies ?? []), e.target.value] }); }}><option value="">Choose a task</option>{snapshot.tasks.filter(t => t.id !== task.id && !state.value.dependencies?.includes(t.id)).map(t => <option key={t.id} value={t.id}>{t.value.title}</option>)}</select></label>{state.value.dependencies?.map(id => <div className="task-dependency" key={id}><span>{snapshot.tasks.find(t => t.id === id)?.value.title ?? 'Unavailable prerequisite'}</span><button type="button" aria-label={`Remove prerequisite ${snapshot.tasks.find(t => t.id === id)?.value.title ?? id}`} onClick={() => change({ dependencies: state.value.dependencies!.filter(d => d !== id) })}>Remove</button></div>)}
    {(state.value.sources ?? []).map((source, index) => <div className="source-edit" key={index}><label>Source name<input required maxLength={100} value={source.label} onChange={e => change({ sources: state.value.sources!.map((s, i) => i === index ? { ...s, label: e.target.value } : s) })}/></label><label>Source URL<input type="url" required maxLength={2000} value={source.url} onChange={e => change({ sources: state.value.sources!.map((s, i) => i === index ? { ...s, url: e.target.value } : s) })}/></label>{/^https?:\/\//.test(source.url) && <a href={source.url} target="_blank" rel="noreferrer">Open source</a>}<button type="button" onClick={() => change({ sources: state.value.sources!.filter((_, i) => i !== index) })}>Remove source</button></div>)}<button type="button" disabled={(state.value.sources?.length ?? 0) >= 10} onClick={() => change({ sources: [...(state.value.sources ?? []), { label: '', url: '' }] })}>Add source link</button>
    </div></details></fieldset>{error && <div className="notice warning" role="alert"><AlertCircle size={18}/><div><p>{error}</p>{conflict && <p>Host version: <strong>{conflict.value.title}</strong> · {conflict.value.status}</p>}{needsReview && <button type="button" onClick={() => { persist({ ...ref.current, revision: conflict?.revision ?? 0, epoch: snapshot.epoch, pending: undefined }); setNeedsReview(false); setError('Your proposal is ready for an explicit save.'); }}>Keep my proposal for review</button>}</div></div>}{task.revision > 0 && <details className="task-more" onToggle={e => { if (e.currentTarget.open) setHistoryOpen(true); }}><summary>Task history</summary>{historyOpen && <TaskHistory taskId={task.id}/>}</details>}<div className="dialog-footer"><span className="metadata">{task.value.trashed ? 'Restore this task from Trash to edit it' : storageError ? 'Keep this window open · browser storage is full' : state.pending ? 'Checking the original save · edits paused' : 'Draft kept on this device'}</span><button type="button" className="quiet" onClick={keepAndClose}>{task.value.trashed ? 'Close' : 'Keep for later'}</button><button type="submit" className="primary" disabled={busy || !!task.value.trashed || needsReview || !state.value.title.trim()}><Save size={17}/>{busy ? 'Saving…' : state.pending ? 'Reconcile save' : 'Save task'}</button></div></form></Dialog>;
}
