import { useEffect,useState } from 'react';
import type { Snapshot } from '../../../packages/domain/contracts';
import { teamRoles,type TeamWork } from '../../../packages/domain/team-work';
import { readLocal,request,saveLocal } from './api';
import './work-tools.css';
import { workRequestRejected } from './work-request';
type Form={projectId:string;title:string;brief:string;maxMinutes:number;steps:{agentId:string;role:typeof teamRoles[number]}[]};
export function TeamWorkPanel({snapshot,projectId,openConversation,active=true}:{snapshot:Snapshot;projectId?:string|null;openConversation:(id:string)=>void;active?:boolean}){
  const key=`e3:team-work:${snapshot.epoch}:${snapshot.deviceId}`;
  const projects=snapshot.projects.filter(p=>p.value.space==='work'&&p.value.workspace?.environment==='local'&&p.value.workspace.folder),agents=(snapshot.records?.agent??[]).filter(a=>!a.value.archived);
  const suggestedMembers=()=>{const used=new Set<string>();return teamRoles.map(role=>{const match=role==='research'?/research|analyst|investigat/i:role==='build'?/build|develop|engineer|implement/i:/review|quality|verif|test/i;const member=agents.find(a=>!used.has(a.id)&&match.test(a.value.position))??agents.find(a=>!used.has(a.id));if(member)used.add(member.id);return {role,agentId:member?.id??''};});};
  const [form,setForm]=useState<Form>(()=>readLocal(key)??{projectId:projectId??projects[0]?.id??'',title:'',brief:'',maxMinutes:10,steps:suggestedMembers()});
  const [runs,setRuns]=useState<TeamWork[]>([]),[selected,setSelected]=useState<string>(),[editing,setEditing]=useState(false),[pending,setPending]=useState<(Form&{requestId:string;epoch:string})|undefined>(()=>readLocal(key+':pending')),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{try{const result=await request<{runs:TeamWork[]}>('work/team');setRuns(result.runs);}catch(e){setError((e as Error).message);}};
  useEffect(()=>{if(!active)return;void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer);},[snapshot.epoch,active]);
  const change=(value:Form)=>{if(!saveLocal(key,value)){setError('Free browser storage before changing this team brief.');return;}setForm(value);};
  const start=async()=>{const cmd=pending??{...form,requestId:crypto.randomUUID(),epoch:snapshot.epoch};if(!saveLocal(key+':pending',cmd)){setError('Free browser storage before starting.');return;}setPending(cmd);setBusy(true);setError('');try{const result=await request<TeamWork>('work/team/start',cmd);setSelected(result.id);setEditing(false);setPending(undefined);saveLocal(key+':pending',null);await load();}catch(e){if(workRequestRejected(e)){saveLocal(key+':pending',null);setPending(undefined);}setError((e as Error).message);}finally{setBusy(false);}};
  const current=runs.find(r=>r.id===selected)??runs[0];
  const control=async(action:'pause'|'resume'|'stop'|'skip')=>{if(!current)return;setBusy(true);setError('');try{await request('work/team/control',{requestId:crypto.randomUUID(),epoch:snapshot.epoch,id:current.id,revision:current.revision,action});await load();}catch(e){setError((e as Error).message);await load();}finally{setBusy(false);}};
  return <section className="team-work-panel"><div className="section-heading"><h3>Team work</h3><button type="button" onClick={()=>setEditing(v=>!v)}>{editing?'Back to runs':'New workflow'}</button></div><p className="metadata">Different members, one shared checkout. Each stage receives the earlier handoffs. You review and publish the final changes.</p>
    {(editing||!runs.length)&&<form onSubmit={e=>{e.preventDefault();void start();}}><fieldset disabled={busy||!!pending}><label>Work Project<select required value={form.projectId} onChange={e=>change({...form,projectId:e.target.value})}><option value="">Choose a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.value.name}</option>)}</select></label>{!projects.length&&<p className="metadata">Create a Work Project from GitHub or a host folder first.</p>}<label>Title<input required maxLength={120} value={form.title} onChange={e=>change({...form,title:e.target.value})}/></label><label>What should the team do?<textarea required rows={4} maxLength={15000} value={form.brief} onChange={e=>change({...form,brief:e.target.value})} placeholder="Describe the outcome and how you will know it works."/></label><div className="team-stage-edit">{form.steps.map((step,i)=><label key={i}>{i+1}. {step.role==='research'?'Research & plan':step.role==='build'?'Implement':'Review'}<select required value={step.agentId} onChange={e=>change({...form,steps:form.steps.map((s,n)=>n===i?{...s,agentId:e.target.value}:s)})}><option value="">Choose an agent</option>{agents.map(a=><option key={a.id} value={a.id}>{a.value.name} · {a.value.position}</option>)}</select></label>)}</div><label>Time limit per stage<select value={form.maxMinutes} onChange={e=>change({...form,maxMinutes:Number(e.target.value)})}>{[5,10,20,30].map(minutes=><option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label><p className="metadata">Implementation can edit the checkout. Research and review use read-only sessions. Uses your existing connected AI allowance.</p></fieldset><button className="primary" disabled={busy||(!pending&&(!form.title.trim()||!form.brief.trim()||!form.projectId||new Set(form.steps.map(s=>s.agentId).filter(Boolean)).size<2))}>{pending?'Reconcile start':'Start team work'}</button></form>}
    {!editing&&current&&<><label>Workflow<select value={current.id} onChange={e=>setSelected(e.target.value)}>{runs.map(r=><option key={r.id} value={r.id}>{r.title} · {r.state}</option>)}</select></label><p><strong>{current.projectName}</strong> · {current.state}</p><p role="status" className="metadata">{current.message}</p><div className="button-row">{current.state==='running'&&<button disabled={busy} onClick={()=>void control('pause')}>Pause after stage</button>}{['paused','attention'].includes(current.state)&&<button disabled={busy} onClick={()=>void control('resume')}>Resume</button>}{!['complete','cancelled','stopping'].includes(current.state)&&<button disabled={busy} onClick={()=>void control('stop')}>Stop team</button>}</div><ol className="team-stages">{current.steps.map((step,i)=><li key={i}><div className="section-heading"><strong>{step.agentName} · {step.role}</strong><small>{step.state}</small></div>{step.message&&<p className="metadata">{step.message}</p>}{step.conversationId&&<button type="button" onClick={()=>openConversation(step.conversationId!)}>Open conversation</button>}{step.result&&<details><summary>Saved handoff</summary><p className="preserve-lines">{step.result}</p></details>}{i===current.next&&['failed','cancelled'].includes(step.state)&&<button disabled={busy} onClick={()=>void control('skip')}>Skip this stage</button>}</li>)}</ol></>}
    {pending&&!editing&&runs.length>0&&<button disabled={busy} onClick={()=>void start()}>Reconcile pending start</button>}{error&&<p role="alert" className="field-error">{error}</p>}
  </section>;
}
