import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { registerModuleTools, type ModulePluginApi } from '../apps/service/module-plugin/index.js';
import { withModulePlugin } from '../apps/service/module-runtime-config.js';
import { phoneRouteAllowed } from '../apps/service/phone-policy.js';
test('tool factory binds native session and server authority, excludes other agents, and rejects stale settings',async t=>{
 const received:any[]=[];const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;received.push({input:JSON.parse(body),authorization:req.headers.authorization});res.setHeader('Content-Type','application/json');res.end(JSON.stringify({state:'applied'}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise<void>(r=>server.close(()=>r())));
 const port=(server.address() as any).port,session:any={sessionId:randomUUID(),permissionMode:'workspace'};let factory:any;
 const api:ModulePluginApi={registrationMode:'full',pluginConfig:{epoch:randomUUID(),bundlePath:'/owned/plugin',url:`http://127.0.0.1:${port}/workspace`,token:'c'.repeat(64)},runtime:{version:'2026.9.2',agent:{session:{getSessionEntry:()=>session}}},registerTool:f=>factory=f};
 registerModuleTools(api);assert.equal(factory({agentId:'other',sessionId:session.sessionId,sessionKey:'foreign'}),null);assert.equal(factory({agentId:'main',sessionId:randomUUID(),sessionKey:'foreign'}),null);
 const tools=factory({agentId:'main',sessionId:session.sessionId,sessionKey:'agent:main:e3:one'});assert.deepEqual(tools.map((t:any)=>t.name),['nova_read','nova_write']);
 const result=await tools[1].execute('native-call',{operation:'records.save',input:{kind:'task'}});assert.equal(result.isError,false);assert.equal(received[0].input.nativeId,session.sessionId);assert.equal(received[0].input.permissionMode,'workspace');assert.equal(received[0].authorization,'Bearer '+'c'.repeat(64));
 await assert.rejects(tools[1].execute('native-call',{operation:'records.save',input:{},nativeId:randomUUID()}));
 session.permissionModePending=true;await assert.rejects(tools[1].execute('later',{operation:'records.save',input:{}}),/access setting changed/);assert.equal(received.length,1);
 api.registrationMode='discovery';factory=undefined;registerModuleTools(api);assert.equal(factory,undefined);
 api.registrationMode='tool-discovery';registerModuleTools(api);assert.equal(typeof factory,'function');
});
test('module plugin preserves owner configuration and follows paired-phone route policy',()=>{
 const epoch=randomUUID(),original:any={plugins:{allow:['owner'],load:{paths:['/owner','/old']},entries:{'edition3-workspace':{enabled:true,config:{bundlePath:'/old'}}}},tools:{deny:['exec']}};
 const config=withModulePlugin(original,epoch,'/new',{url:'http://127.0.0.1:4383/workspace',token:'b'.repeat(64)});assert.deepEqual(config.plugins?.load?.paths,['/owner','/new']);assert.deepEqual(config.tools,original.tools);assert.deepEqual(original.plugins.load.paths,['/owner','/old']);
 assert.equal(withModulePlugin({plugins:{enabled:false}},epoch,'/new',{url:'unused',token:'unused'}).plugins?.enabled,false);
 assert.equal(phoneRouteAllowed('/api/assistant/module-action','POST'),true);assert.equal(phoneRouteAllowed('/workspace','POST'),false);
});
test('source image readings reach the native model as image blocks without duplicating pixels into text or details',async t=>{
 const pixels=Buffer.from('fixture image bytes').toString('base64');
 const server=createServer(async(req,res)=>{for await(const _part of req){}res.setHeader('Content-Type','application/json');res.end(JSON.stringify({page:2,pages:4,view:'image',image:{mimeType:'image/jpeg',data:pixels,width:200,height:100},notes:['This page only.']}));});
 await new Promise<void>(ok=>server.listen(0,'127.0.0.1',ok));t.after(()=>new Promise<void>(ok=>server.close(()=>ok())));
 const sessionId=randomUUID();let factory:any;
 registerModuleTools({registrationMode:'full',pluginConfig:{epoch:randomUUID(),bundlePath:'/owned/plugin',url:`http://127.0.0.1:${(server.address() as any).port}/workspace`,token:'c'.repeat(64)},runtime:{version:'2026.9.2',agent:{session:{getSessionEntry:()=>({sessionId,permissionMode:'read-only'})}}},registerTool:fn=>factory=fn});
 const tool=factory({agentId:'edition3-assignment',sessionId,sessionKey:'agent:edition3-assignment:e3-assignment-fixture'})[0];
 const result=await tool.execute('source-call',{operation:'sources.read',input:{fileId:randomUUID(),page:2,view:'image'}});
 assert.equal(result.isError,false);assert.deepEqual(result.content[1],{type:'image',mimeType:'image/jpeg',data:pixels});
 assert(!result.content[0].text.includes(pixels));assert(!JSON.stringify(result.details).includes(pixels));assert.equal(result.details.page,2);
});
test('visual hook forwards actual image results only from the exact main session and run', async t => {
 const received:any[]=[];const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;received.push({url:req.url,body:JSON.parse(body)});res.end('{}');});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise<void>(r=>server.close(()=>r())));
 const sessionId=randomUUID(),epoch=randomUUID();let hook:any;
 registerModuleTools({registrationMode:'full',pluginConfig:{epoch,bundlePath:'/owned/plugin',url:`http://127.0.0.1:${(server.address() as any).port}/workspace`,token:'b'.repeat(64)},runtime:{version:'2026.9.2',agent:{session:{getSessionEntry:()=>({sessionId})}}},registerTool:()=>{},on:(name,fn)=>{assert.equal(name,'after_tool_call');hook=fn;}});
 const context={agentId:'main',sessionId,sessionKey:'agent:main:e3:test',runId:randomUUID(),toolCallId:'actual-call'},event={toolName:'computer-use.screenshot',result:{content:[{type:'image',mimeType:'image/png',data:'aGVsbG8='}]}};
 await hook(event,{...context,sessionId:randomUUID()});await hook(event,{...context,agentId:'other'});await hook({...event,error:'failed'},context);await hook({...event,result:{path:'/private/file'}},context);assert.equal(received.length,0);
 await hook(event,context);assert.equal(received.length,1);assert.equal(received[0].url,'/workspace/observation');assert.equal(received[0].body.runId,context.runId);assert.equal(received[0].body.toolCallId,'actual-call');assert.equal(received[0].body.image.data,'aGVsbG8=');
});

test('trusted native policy checks exact session and blocks failed bridge checks; capability requires the real policy API', async t => {
 const received:any[]=[];let offline=false;
 const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;received.push({path:req.url,body:JSON.parse(body)});res.setHeader('Content-Type','application/json');if(offline){res.writeHead(503);res.end('{}');return;}res.end(JSON.stringify({block:received.at(-1).body.toolName==='exec',blockReason:'Plan review required'}));});
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise<void>(r=>server.close(()=>r())));
 const epoch=randomUUID(),sessionId=randomUUID();let policy:any,method:any;
 const api:ModulePluginApi={registrationMode:'full',pluginConfig:{epoch,bundlePath:'/owned/plugin',url:`http://127.0.0.1:${(server.address() as any).port}/workspace`,token:'b'.repeat(64)},runtime:{version:'2026.9.2',agent:{session:{getSessionEntry:()=>({sessionId})}}},registerTool:()=>{},registerTrustedToolPolicy:value=>policy=value,registerGatewayMethod:(name,value)=>{assert.equal(name,'e3.workspace.policy');method=value;}};
 registerModuleTools(api);assert.equal(policy.id,'nova-plan-read-only');
 let handshake:any;method({params:{nativeKey:'agent:main:e3:fixture',nativeId:sessionId},respond:(...args:any[])=>handshake=args});assert.equal(handshake[0],true);assert.equal(handshake[1].researchWorkflow,'chat-research-v1');
 const context={agentId:'main',sessionId,sessionKey:'agent:main:e3:fixture',runId:randomUUID()};
 assert.equal((await policy.evaluate({toolName:'exec'},context)).block,true);assert.equal((await policy.evaluate({toolName:'read'},context)).block,false);
 assert.equal(received[0].path,'/workspace/policy');assert.equal(received[0].body.nativeId,sessionId);assert.equal(received[0].body.runId,context.runId);
 const count=received.length;assert.equal(await policy.evaluate({toolName:'exec'},{...context,agentId:'edition3-assignment'}),undefined);assert.equal(received.length,count);
 offline=true;assert.equal((await policy.evaluate({toolName:'read'},context)).block,true);assert.equal(await policy.evaluate({toolName:'exec'},{...context,sessionKey:'agent:main:unrelated'}),undefined);
 let response:any;method({params:{nativeKey:context.sessionKey,nativeId:sessionId},respond:(...args:any[])=>response=args});assert.equal(response[0],true);assert.equal(response[1].protected,true);
 method({params:{nativeKey:context.sessionKey,nativeId:randomUUID()},respond:(...args:any[])=>response=args});assert.equal(response[0],false);
 let registered=false;registerModuleTools({...api,registerTrustedToolPolicy:undefined,registerGatewayMethod:()=>{registered=true;}});assert.equal(registered,false);
});

test('research producer consumes the trusted actual call/run binding and never guesses from the factory session', async t => {
 const received:any[]=[];let allow=true,revisionConflict=false,policyHold:Promise<void>|undefined,currentEstimate:any;
 const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;received.push({path:req.url,body:JSON.parse(body)});res.setHeader('Content-Type','application/json');if(req.url?.endsWith('/policy')){await policyHold;res.end(JSON.stringify({block:!allow}));return;}if(revisionConflict){res.writeHead(409);res.end(JSON.stringify({code:'research_progress_revision',message:'Use the current revision.',current:currentEstimate}));return;}res.end(JSON.stringify({saved:true,revision:1}));});
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise<void>(r=>server.close(()=>r())));
 const epoch=randomUUID(),sessionId=randomUUID(),nativeKey='agent:main:e3:research';let policy:any,factory:any,session:any={sessionId,permissionMode:'read-only'};
 const api:ModulePluginApi={registrationMode:'full',pluginConfig:{epoch,bundlePath:'/owned/plugin',url:`http://127.0.0.1:${(server.address() as any).port}/workspace`,token:'b'.repeat(64),sessionBindings:[{nativeKey,nativeId:sessionId}]},runtime:{version:'2026.9.2',agent:{session:{getSessionEntry:()=>session}}},registerTool:(fn,options)=>{if(options.names.includes('nova_research_progress'))factory=fn;},registerTrustedToolPolicy:value=>policy=value,registerGatewayMethod:()=>{}};
 registerModuleTools(api);
 assert.ok(JSON.parse(readFileSync(new URL('../apps/service/module-plugin/openclaw.plugin.json',import.meta.url),'utf8')).contracts.tools.includes('nova_research_progress'));
 const context={agentId:'main',sessionId,sessionKey:nativeKey},tool=factory(context),runId=randomUUID(),toolCallId='estimate-1';
 const input={expectedRevision:0,activity:'Inspecting the current field study',basis:'Study interpretation outweighs reading the brief specification.',items:[{id:'study',title:'Interpret the measured field study',effort:8,status:'active'},{id:'report',title:'Write and verify the report',effort:5,status:'pending'}]};
 assert.equal(factory({...context,agentId:'other'}),null);assert.equal(tool.name,'nova_research_progress');assert.equal(tool.parameters.additionalProperties,false);
 await assert.rejects(tool.execute(toolCallId,input),/run could not be verified/);assert.equal(received.length,0);
 assert.equal((await policy.evaluate({toolName:tool.name},{...context,runId})).block,true);
 assert.equal((await policy.evaluate({toolName:tool.name,runId:randomUUID(),toolCallId},{...context,runId,toolCallId})).block,true);
 assert.equal((await policy.evaluate({toolName:tool.name,runId,toolCallId},{...context,runId,toolCallId})).block,false);
 const result=await tool.execute(toolCallId,input);assert.equal(result.details.revision,1);
 const sent=received.at(-1);assert.equal(sent.path,'/workspace/research-progress');assert.equal(sent.body.runId,runId);assert.equal(sent.body.toolCallId,toolCallId);assert.equal(sent.body.nativeId,sessionId);assert.equal(sent.body.epoch,epoch);assert.deepEqual(sent.body.estimate,input);
 await assert.rejects(tool.execute(toolCallId,input),/run could not be verified/);
 allow=false;assert.equal((await policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'blocked'})).block,true);await assert.rejects(tool.execute('blocked',input),/run could not be verified/);
 allow=true;await policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'conflict'});assert.equal((await policy.evaluate({toolName:tool.name},{...context,runId:randomUUID(),toolCallId:'conflict'})).block,true);await assert.rejects(tool.execute('conflict',input),/run could not be verified/);
 await policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'expired'});const time=Date.now();const clock=t.mock.method(Date,'now',()=>time+60001);await assert.rejects(tool.execute('expired',input),/run could not be verified/);clock.mock.restore();
 let releasePolicy!:()=>void;policyHold=new Promise<void>(resolve=>releasePolicy=resolve);const first=policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'overlap'});
 const second=policy.evaluate({toolName:tool.name},{...context,runId:randomUUID(),toolCallId:'overlap'});releasePolicy();assert.deepEqual((await Promise.all([first,second])).map(result=>result.block),[true,true]);policyHold=undefined;await assert.rejects(tool.execute('overlap',input),/run could not be verified/);
 const cancelled=new AbortController();cancelled.abort();await policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'cancelled'});await assert.rejects(tool.execute('cancelled',input,cancelled.signal),{name:'AbortError'});
 const nativeCancel=new AbortController();await policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'native-cancelled',abortSignal:nativeCancel.signal});nativeCancel.abort();await assert.rejects(tool.execute('native-cancelled',input),{name:'AbortError'});
 revisionConflict=true;currentEstimate={revision:3,estimate:{activity:input.activity,basis:input.basis,items:input.items}};await policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'stale'});const conflict=await tool.execute('stale',input);assert.equal(conflict.isError,true);assert.deepEqual(conflict.details.current,currentEstimate);revisionConflict=false;
 await policy.evaluate({toolName:tool.name},{...context,runId,toolCallId:'changed'});session={...session,sessionId:randomUUID()};await assert.rejects(tool.execute('changed',input),/conversation changed/);
 assert.equal(received.filter(item=>item.path==='/workspace/research-progress').length,2);
});
