// Explicit existing workspace routes. New endpoints default to desktop-only.
const routes = new Set(`
GET /api/work/team
GET /api/work/team/handoff
POST /api/work/team/start
POST /api/work/team/control
GET /api/work/browser
POST /api/work/browser/configure
GET /api/work/browser/observe
POST /api/work/browser/action
GET /api/work/github
POST /api/work/github
GET /api/work/repositories
GET /api/work/branches
GET /api/work/state
POST /api/work/checkout
GET /api/work/review
POST /api/work/publish
POST /api/work/reconcile
GET /api/accounts
GET /api/companions/state
POST /api/companions/revoke
GET /api/agent-routines/state
GET /api/agent-skills/installed
GET /api/agent-skills/proposal
GET /api/agent-skills/proposal-events
GET /api/agent-skills/proposals
GET /api/agent-skills/reviews
GET /api/agents/hub
POST /api/agents/hub/layout
GET /api/agents/meetings
POST /api/agents/meetings
GET /api/assignments/state
GET /api/assignments/approvals
GET /api/assistant/models
GET /api/assistant/service
GET /api/software-update
GET /api/assistant/outputs
GET /api/assistant/state
GET /api/assistant/voice/catalog
GET /api/assistant/read-aloud/catalog
POST /api/assistant/read-aloud/speak
GET /api/home/weather
GET /api/home/weather/locations
GET /api/calendar/state
GET /api/snapshot
GET /api/content/library
GET /api/profile/progress
GET /api/profile/history
POST /api/profile/quests
GET /api/content/state
GET /api/content/result
GET /api/content/package
POST /api/content/workspace
POST /api/agent-routines/preview
POST /api/agent-routines/save
POST /api/agent-skills/keep-review
POST /api/assignments/acknowledge
POST /api/assignments/start
POST /api/assignments/stop
POST /api/assistant/approval/check
POST /api/assistant/approval/resolve
POST /api/assistant/artifact/read
POST /api/assistant/artifact/save
POST /api/assistant/browse
POST /api/assistant/cancel
POST /api/assistant/conversation/edit
POST /api/assistant/conversation/fork
POST /api/assistant/conversation/recover-settings
POST /api/assistant/conversation/remove
POST /api/assistant/conversations
POST /api/assistant/dictation/audio
POST /api/assistant/dictation/caption
POST /api/assistant/dictation/end
POST /api/assistant/dictation/offer
POST /api/assistant/dictation/start
POST /api/assistant/draft/organize
POST /api/assistant/draft/remove
POST /api/projects/organize
POST /api/assistant/goal
POST /api/assistant/memory
POST /api/assistant/message-pin
POST /api/assistant/outputs
POST /api/assistant/question/check
POST /api/assistant/question/dismiss
POST /api/assistant/question/resolve
POST /api/assistant/queue
POST /api/assistant/queue/edit
POST /api/assistant/queue/order
POST /api/assistant/queue/run
POST /api/assistant/queue/state
POST /api/assistant/search
POST /api/assistant/steer
POST /api/assistant/module-actions
POST /api/assistant/module-action
POST /api/assistant/plan/approve
POST /api/assistant/plan/amend
POST /api/assistant/plan/hold
POST /api/assistant/plan/cancel
POST /api/assistant/submit
POST /api/assistant/voice/consult
POST /api/assistant/voice/end
POST /api/assistant/voice/finals
POST /api/assistant/voice/offer
POST /api/assistant/voice/pulse
POST /api/assistant/voice/start
POST /api/assistant/retained/export
POST /api/attachments
POST /api/transfers/start
POST /api/transfers/piece
POST /api/calendar/followups
POST /api/calendar/groups/action
POST /api/calendar/groups/prepare
POST /api/calendar/groups/read
POST /api/calendar/groups/reconcile
POST /api/calendar/local
POST /api/calendar/refresh
POST /api/calendar/reminders/action
POST /api/calendar/reminders/delivery
POST /api/calendar/selection
POST /api/calendar/sources
POST /api/calendar/write/confirm
POST /api/calendar/write/open
POST /api/calendar/write/prepare
POST /api/calendar/write/read
POST /api/calendar/write/reconcile
POST /api/commands
POST /api/content/from-assignment
POST /api/contacts/read
POST /api/contacts/address-books
POST /api/contacts/address-browse
POST /api/contacts/address-import
POST /api/contacts/address-sync
POST /api/contacts/address-link
POST /api/contacts/crm
POST /api/contacts/activity
POST /api/contacts/organization
POST /api/contacts/photo
POST /api/contacts/merge
POST /api/contacts/restore
POST /api/content/from-output
POST /api/mail/contacts/link
POST /api/mail/contacts/prepare
POST /api/mail/delivery/confirm
POST /api/mail/delivery/file
POST /api/mail/delivery/open
POST /api/mail/delivery/prepare
POST /api/mail/delivery/read
POST /api/mail/delivery/reconcile
POST /api/mail/files
POST /api/mail/files/read
POST /api/mail/index/command
POST /api/mail/index/read
POST /api/mail/images
POST /api/mail/read
POST /api/mail/triage/confirm
POST /api/mail/triage/displayed
POST /api/mail/triage/prepare
POST /api/mail/triage/read
POST /api/mail/triage/reconcile
POST /api/records/follow-up
POST /api/records/history
POST /api/tasks/focus
POST /api/tasks/calendar-completion
POST /api/tasks/suggestions
POST /api/tasks/suggestions/stop
POST /api/tasks/history
POST /api/tasks/order
POST /api/tasks/reminders/action
POST /api/tasks/reminders/delivery
`.trim().split('\n'));
const dynamic = /^\/api\/(?:attachments|tasks\/suggestions|calendar\/local|assignments\/(?:attempt|check)|assistant\/(?:history|retained|goal|reconcile|access|dictation|voice|voice\/recover))\/[a-f0-9-]{36}$/;
export function phoneRouteAllowed(path: string, method: string) { return routes.has(method + ' ' + path) || method === 'GET' && (dynamic.test(path) || /^\/api\/assistant\/work-changes\/[a-f0-9-]{36}$/.test(path) || /^\/api\/assistant\/observation\/[a-f0-9-]{36}(?:\/[a-f0-9]{64})?$/.test(path)); }
