import { z } from 'zod';
import { accountIdSchema, type ConnectedAccount } from './accounts.js';
import { timezone } from './tasks.js';
import { contactId } from './crm.js';
import type { Contact } from './workspace-records.js';
export const sharedContactSchema = z.object({ name: z.string().trim().min(1).max(240), emails: z.array(z.email().max(254)).max(100), phone: z.string().max(80), organization: z.string().max(240), position: z.string().max(240) }).strict();
export type SharedContact = z.infer<typeof sharedContactSchema>;
export const sharedFields = ['name', 'emails', 'phone', 'organization', 'position'] as const;
export type SharedField = typeof sharedFields[number];
export const sharedLabels: Record<SharedField, string> = { name: 'Name', emails: 'Email addresses', phone: 'Primary phone', organization: 'Primary organization', position: 'Job title' };
export const sharedContact = (c: Contact): SharedContact => ({ name: c.name, emails: [...new Set([c.email, ...(c.otherEmails ?? [])].filter(Boolean))], phone: c.phone, organization: c.organization, position: c.position });
export const withSharedContact = (c: Contact, v: SharedContact): Contact => ({ ...c, name: v.name, email: v.emails[0] ?? '', otherEmails: v.emails.slice(1), phone: v.phone, organization: v.organization, position: v.position, otherOrganizations: c.otherOrganizations?.filter(s => s.toLocaleLowerCase() !== v.organization.toLocaleLowerCase()) });
const account = z.object({ epoch: z.uuid(), accountId: accountIdSchema, generation: z.uuid() });
export const addressBrowseSchema = account.extend({ cursor: z.string().max(20000).optional(), folder: z.string().max(1000).optional() }).strict();
export const addressImportSchema = account.extend({ requestId: z.uuid(), reviewId: z.uuid(), entries: z.array(z.object({ remoteId: z.string().min(1).max(1000), target: z.union([z.literal('new'), contactId]), revision: z.number().int().nonnegative() }).strict()).min(1).max(100), mode: z.enum(['read', 'both']), timezone: timezone.default('UTC') }).strict();
export const addressSyncSchema = account.extend({ requestId: z.uuid() }).strict();
export const addressLinkSchema = account.extend({ requestId: z.uuid(), linkId: z.string().regex(/^link:[a-f0-9]{40}$/), revision: z.number().int().positive(), action: z.enum(['pause', 'resume', 'resolve']), choices: z.partialRecord(z.enum(sharedFields), z.enum(['local', 'remote'])).optional() }).strict();
export type AddressLink = { id: string; accountId: string; generation: string; remoteId: string; contactId: string; revision: number; base: SharedContact; mode: 'read' | 'both'; state: 'synced' | 'paused' | 'conflict' | 'missing' | 'unknown' | 'error'; checkedAt: string; message?: string; conflict?: { local: SharedContact; remote: SharedContact; fields: SharedField[] }; intent?: { before: SharedContact; value: SharedContact; changed: SharedField[]; startedAt: string; localRevision: number; etag: string } };
export type AddressBookState = { accounts: ConnectedAccount[]; links: AddressLink[]; running: string[] };
export type AddressReview = { id: string; accountId: string; generation: string; entries: { remoteId: string; value: SharedContact; matches: { id: string; name: string; organization: string; revision: number }[]; linked?: string; unavailable?: string }[]; next?: string; folders?: { id: string; name: string }[]; folder?: string; skipped: number };
