/** Guidance only. Native tool policy, per-call approval and driver scope enforce access.
 * Capture these exact bytes with new work so revisions cannot rewrite earlier inputs. */
export const computerControlGuidance = `Computer control, only when the requested task and existing authorization allow it:
Use only the available tools and authorized apps/windows. These instructions grant no access and do not override a read-only task. Keep the same session and exact process/window identity throughout.
An app process starting does not mean its window is ready. If launch returns no usable window, use the available window-discovery tool filtered to that exact authorized PID; make only bounded readiness observations within the existing deadline. Select a live ordinary window from the returned metadata before activation or input. Do not list the whole desktop, relaunch repeatedly, borrow an earlier window ID or invent one. If scoped discovery is unavailable or readiness cannot be established, stop and report the missing prerequisite.
When calling native tools through Code Mode, inspect the actual result type. A result may already be flattened to a string: forward it with text(result). Do not read only result.content or result.structuredContent from a string, because that silently discards the observation. For a structured MCP result, forward its text and image content with the available output helpers. Do not assume JSON.parse accepts mixed prose such as a structuredContent: prefix. An empty script output is not evidence of an empty app: check result handling before requesting another observation. A text-only result does not prove that you have seen its screenshot.
Keep observations bounded to the relevant window and controls using supported query, max_elements and max_depth options. Preserve exact element identities, values, incomplete-tree warnings and refused/degraded route information. Request further detail only when the current observation is insufficient for the next action; never treat omitted controls as absent.
An unresolved accessibility tree does not invalidate a separately verified exact-window image. Within an already authorized foreground route, use a supported keyboard action or controls grounded in that current image, then verify the effect. Recompute pixel targets from the latest visible image and its coordinate contract; do not reuse coordinates across changed rendering, scaling or window geometry. If the image was not actually delivered or its geometry is unclear, request a fresh scoped observation or stop. Never use an observation fallback to bypass a denied resource or input action.
Observe the target before acting. Perform one input action, then obtain fresh state and verify its expected effect before choosing the next input. Use controls from the latest snapshot; never batch a sequence against old element handles. A successful tool response or effect="unverifiable" does not establish that the app changed. Do not repeat an action with an uncertain effect.
If input is refused, or the target/effect can no longer be observed, stop further input. You may take a fresh authorized observation to explain the blocker; do not continue the remaining planned clicks, guess coordinates, reset the app or switch to another app, tool or delivery route to bypass the refusal.
Use foreground activation or delivery only within existing authorization. Verify exact-window activation, then observe again. Earlier activation does not prove the window remains accessible during later actions.
Reserve time to end the session with the available cleanup tool before the assignment deadline, including when blocked. Report the last observed state, the action whose effect is unconfirmed and the remaining work. Claim completion only from the observed result, never from a computed or expected answer.`;
