import { z } from 'zod';
export const workModeSchema = z.enum(['chat', 'plan', 'research', 'image', 'goal']);
export type WorkMode = z.infer<typeof workModeSchema>;
/** Captured verbatim on new Chat research turns so saved envelopes stay stable. */
export const researchProgressGuidance = 'For the preparation proposal, provide stepTitles with one short action title per step in the same order, usually 3 to 7 words, such as Find primary sources, Compare the evidence, or Write the report. Keep full explanations and source requirements in steps, not in the titles. Keep this approved broad outline stable during the investigation. Update its exact titles (or full steps for older plans) through update_plan or progress_card only when their real status changes. Separately, at the start of an approved investigation and as concrete work advances, use nova_research_progress to report a task-aware workload estimate. This is an estimate, not a measured percentage or remaining-time promise. Break the actual investigation into concrete source checks, evidence comparisons, verification and report work, including useful subtasks within each broad heading. Give stable IDs and estimate each item\'s relative effort from its actual complexity and scope; do not automatically give headings equal weights or use a fixed phase-percentage schedule. Supply a brief public basis for the estimate. Mark an item complete only after its real work is done. Keep completed items and their effort unchanged; revise remaining work or add discovered work when the evidence requires it. Do not manufacture tiny tasks to make the bar move. Keep at least one unfinished report/verification item until finishing the report; the native final response confirms overall completion. Use expectedRevision 0 initially, then the revision returned by the last accepted update. On a revision conflict, read the returned current estimate and reconcile rather than overwrite blindly. Report one short concrete current activity, such as checking a particular claim or comparing specific source findings. Update it when work changes; never describe finished work as current. This is public activity, not private reasoning. Do not invent completed work, source counts, tool results or a direct percentage. If no supported workload estimate is available, continue with truthful activity updates without fabricating a fill value.';
/** Versioned by its captured researchWorkflow; never used to reconstruct older research turns. */
export function chatResearchInstructions(approved: boolean): string {
  return approved
    ? 'The owner started the reviewed Deep research plan. Investigate that exact scope using actual available search and source-reading tools. Begin with structured update_plan or progress_card steps based on the approved research plan, and update them only as their real work advances. Search iteratively, read the original sources, compare the relevant evidence and verify important claims. Prefer primary and current sources, follow promising leads, and resolve contradictions where possible. Give concise progress messages with concrete findings or changes of direction. Produce a comprehensive, well-organized report that answers the agreed question, with descriptive headings, a clear synthesis, limitations, and direct source links near the claims they support. Distinguish cited evidence from inference and uncertainty. Cite only sources actually inspected; never invent sources, counts, progress or an investigation that did not occur. If a required tool or source is unavailable, explain the exact gap and provide only the findings the available evidence supports. This is a read-only investigation: do not change files or external systems, execute commands, or delegate work. Completion means the actual investigation and final report are finished, not that the preparation plan was saved.'
    : 'The owner selected Deep research in Chat. First establish the scope of the requested research. Inspect supplied context as needed, and ask only material clarifying questions through request_user_input. Once the scope is clear, use nova_plan to save a research proposal: a descriptive title; a concise summary of the research question and intended result; concrete investigation steps and source approach; any assumptions; and evidence/verification criteria. Do not begin web searches or source fetching in this preparation turn. Do not substitute a finished report for the proposal or claim research already happened. After saving the proposal, finish this turn. Nova will show the plan with Start research, Edit and Cancel, and a visible 45-second automatic-start period. The service admits the exact saved version before research may begin; a chat message saying yes is not approval. Editing or cancelling pauses that automatic start. Do not perform the investigation or modify files and external systems during preparation.';
}
export const workModes: { id: WorkMode; label: string; description: string }[] = [
  { id: 'chat', label: 'Chat', description: 'Ask, create, and get things done' },
  { id: 'image', label: 'Image', description: 'Create an image from your description' },
  { id: 'goal', label: 'Goal', description: 'Set an objective to keep pursuing' },
  { id: 'plan', label: 'Plan', description: 'Think through the steps before acting' },
  { id: 'research', label: 'Research', description: 'Investigate and compare sources' },
];
/** Captured with the submitted draft; it never grants additional tool permissions. */
export function workModeInstructions(mode?: WorkMode): string {
  if (mode === 'goal') return 'The owner explicitly selected Goal. Pursue this objective until its required outcome is verified. Use nova_read with operation goal.read and input {} to inspect the saved goal. Once achieved, use nova_write with operation goal.update and input {goalId: the exact current goal ID, status: "complete"}; report "blocked" only after the same blocker recurs on at least three consecutive Goal turns. This status-only action is available in read-only Goal requests and grants no permission to edit files or workspace records. Do not confuse completed planning steps or a final reply with a completed goal. Confirm the saved goal status from the tool result, then provide the requested visible answer. If no supported goal tool is available, say that the status could not be updated; never claim it was saved.';
  if (mode === 'image') return 'The owner selected Image. Generate an actual image with the available image-generation tool from their description and supplied reference attachments. Return the generated image in the conversation. Do not substitute a text-only description or claim an image exists without a successful tool result. If generation is unavailable, explain the missing capability plainly.';
  if (mode === 'plan') return 'The owner selected Plan mode. Produce a concrete plan before implementation: clarify the intended outcome, inspect relevant available context, identify dependencies and meaningful decisions, and propose ordered steps and verification. Ask only necessary questions. Do not implement the plan, change files, publish, or take external actions in this turn. Ask necessary clarifying questions through request_user_input so the owner can choose or write an answer. Once decisions are settled, use nova_plan to save a structured proposal with title, summary, ordered steps, assumptions, and verification criteria. Finish the planning turn after saving it. The app asks "Implement this plan?" for the saved proposal; a chat message saying yes or a progress update does not authorize implementation. Only read-only tools are available until the exact saved proposal is approved.';
  if (mode === 'research') return 'The owner selected Research mode. Clarify material scope questions through request_user_input when needed, then briefly explain your approach and investigate using available search and source-reading tools. Keep progress concise and tied to actual work. For substantial assignments, organize the final report with a descriptive heading, findings, limitations and a concise conclusion; keep simple research answers short. Prefer primary sources, compare relevant evidence, check current facts, and cite direct source links near supported claims. Distinguish evidence, inference, uncertainty, and missing access. Do not invent citations or claim research that was not performed. If search is unavailable, say so clearly and limit the answer accordingly. Produce a useful sourced synthesis; do not modify external systems.';
  return '';
}
